### ISSUE TITLE
Why every app I made using Sketchware Pro always detected as a Trojan?

### ISSUE THREAD

**Issue by agan0naga** [Sketchware-Pro/Sketchware-Pro#637] opened 2022-11-10 05:53 UTC
Everytime I made an app I using Sketchware Pro,
Avast AV always detecting it contain a Trojan Virus

How to solve this?

**Comment by TheRemakerMan** [comment] 2022-11-10 05:56
By not using Antivirus in 2022.

**Comment by JavkhlanK** [comment] 2022-11-10 06:14
Those are probably just false-positives. Did you let those AVs scan debug apps? That might be why, as debug apps use a common, well-known signature. Try exporting your projects, that will probably fix it.

**Comment by subhash16** [comment] 2022-11-11 03:32
Give a swb file

**Comment by agan0naga** [comment] 2022-11-11 05:38
@JavkhlanK thx..
Yap, maybe it because the debug apps..
I try to sign using "Create Release Keystore" but the signed app can't be installed.
The error is "There was a proble parsing the package"

any solutions?
(Besides the export solutions)

**Comment by JavkhlanK** [comment] 2022-11-11 06:12
Export your project but don't sign it, then sign that file with e.g. MT Manager or apk-signer.

**Comment by subhash16** [comment] 2022-11-11 06:43
SIR, Can you give the link of MT manager.

**Comment by agan0naga** [comment] 2022-11-11 08:46
@JavkhlanK in export option there's a choice to export to android studio..
but when I open in android studio there's so much error when I try to build..
Maybe you or the sketchware pro team have a "GOOD" tutorial about how to exported and run with Android Studio?

**Comment by JavkhlanK** [comment] 2022-11-11 12:28
> SIR, Can you give the link of MT manager.

I found this Telegram channel with translated changelogs and APKs: https://t.me/mtmanager

**Comment by JavkhlanK** [comment] 2022-11-11 12:29
> @JavkhlanK in export option there's a choice to export to android studio..
> but when I open in android studio there's so much error when I try to build..
> Maybe you or the sketchware pro team have a "GOOD" tutorial about how to exported and run with Android Studio?

We'll try to fix those issues. Meanwhile, fixing those problems yourself is a good exercise for using Android Studio.

**Comment by TechnicalStudioDevelopers** [comment] 2022-11-13 03:59
I am also facing the same problem with pro guard when I enable pro guard then after installing it shows me this app contains Trojan .

**Comment by JavkhlanK** [comment] 2022-11-14 06:16
Looks a duplicate of #403. It's a false-positive by that anti-virus scanner, and maybe you can submit a False-positive detection request to its developers.

**Closed** 2022-11-14 06:16 UTC
Labels: duplicate, answered, question

**Comment by TechnicalStudioDevelopers** [comment] 2022-11-14 06:17
But If it provide false reports then user will uninstall my app😞😞

**Comment by JavkhlanK** [comment] 2022-11-14 06:21
Try sending a false-positive detection claim to the anti-virus developer then.

**Comment by TechnicalStudioDevelopers** [comment] 2022-11-14 06:23
Anylink to submit report?

**Comment by JavkhlanK** [comment] 2022-11-14 06:24
It depends on which anti-virus you used, I don't know that. Just look at its homepage and search for something like 'false-positive scan'.

**Comment by subhash16** [comment] 2022-11-14 06:52
Please give sample swb file of yours I will check
