### ISSUE TITLE
ItemVerticalScrollView ClassCastException

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#563] opened 2022-09-02 06:53 UTC
when i want to keep only Center_Horizontal  then i got this error.
![Screenshot_2022-09-02-12-51-19-97_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/188076406-bf5b326b-c75f-4a83-8218-3c7bd98f3ba9.jpg)

java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:195)
	at com.besome.sketch.editor.view.item.ItemVerticalScrollView.onMeasure(Unknown Source:0)
	at android.view.View.measure(View.java:25792)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7065)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25792)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25792)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7065)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25792)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25792)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25792)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25792)
	at androidx.viewpager.widget.ViewPager.onMeasure(Unknown Source:243)
	at android.view.View.measure(View.java:25792)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7065)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.a(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:320)
	at android.view.View.measure(View.java:25792)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25792)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25792)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(Unknown Source:262)
	at android.view.View.measure(View.java:25792)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25792)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7065)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:152)
	at android.view.View.measure(View.java:25792)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7065)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25792)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7065)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25792)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7065)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25792)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7065)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:832)
	at android.view.View.measure(View.java:25792)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3788)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2546)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2808)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2266)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8846)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1473)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1270)
	at android.view.Choreographer.doFrame(Choreographer.java:981)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1458)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8299)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by AndroXStudiO** [comment] 2022-09-02 06:59
Here My Full XML code!

<LinearLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	xmlns:tools="http://schemas.android.com/tools"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:orientation="vertical">
	<ScrollView
		android:id="@+id/vscroll1"
		android:layout_width="match_parent"
		android:layout_height="match_parent">
		<LinearLayout
			android:id="@+id/linear1"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:paddingLeft="15dp"
			android:paddingTop="8dp"
			android:paddingRight="15dp"
			android:paddingBottom="25dp"
			android:background="#FFFFFF"
			android:gravity="center_horizontal|center_vertical"
			android:orientation="vertical">
			<com.google.android.material.textfield.TextInputLayout
				android:id="@+id/textinputlayout1"
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				android:layout_marginLeft="10dp"
				android:layout_marginTop="18dp"
				android:layout_marginRight="10dp"
				android:padding="2dp"
				style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
				app:startIconDrawable="@drawable/ic_call_black"
				app:boxCornerRadiusBottomEnd="8dp"
				app:boxCornerRadiusTopEnd="8dp"
				app:boxCornerRadiusBottomStart="8dp"
				app:boxCornerRadiusTopStart="8dp"
				app:boxStrokeColor="#ffb300"
				app:hintTextColor="#ffb300">
				<EditText
					android:id="@+id/edittext3"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:padding="15dp"
					android:gravity="center_vertical"
					android:text="+880"
					android:textSize="16sp"
					android:textColor="#1F1F1F"
					android:hint="Phone Number"
					android:textColorHint="#454746"
					android:singleLine="true"
					android:inputType="phone"
					android:maxLength="18"
					android:maxLines="1"
					android:digits="+0123456789" />
			</com.google.android.material.textfield.TextInputLayout>
			<LinearLayout
				android:id="@+id/linear8"
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				android:layout_marginLeft="10dp"
				android:layout_marginTop="5dp"
				android:layout_marginRight="10dp"
				android:layout_marginBottom="5dp"
				android:paddingLeft="2dp"
				android:paddingRight="2dp"
				android:gravity="center_vertical"
				android:orientation="horizontal">
				<com.google.android.material.textfield.TextInputLayout
					android:id="@+id/textinputlayout2"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:padding="2dp"
					android:gravity="center_horizontal|center_vertical"
					android:layout_weight="1"
					style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
					app:startIconDrawable="@drawable/ic_password"
					app:boxCornerRadiusBottomEnd="8dp"
					app:boxCornerRadiusTopEnd="8dp"
					app:boxCornerRadiusBottomStart="8dp"
					app:boxCornerRadiusTopStart="8dp"
					app:boxStrokeColor="#ffb300"
					app:hintTextColor="#ffb300">
					<EditText
						android:id="@+id/edittext4"
						android:layout_width="match_parent"
						android:layout_height="wrap_content"
						android:padding="15dp"
						android:gravity="center_vertical"
						android:textSize="16sp"
						android:textColor="#1F1F1F"
						android:hint="Verification Code"
						android:textColorHint="#454746"
						android:singleLine="true"
						android:inputType="phone"
						android:enabled="false"
						android:layout_weight="1"
						android:maxLength="11"
						android:maxLines="1"
						android:digits="+0123456789" />
				</com.google.android.material.textfield.TextInputLayout>
			</LinearLayout>
			<LinearLayout
				android:id="@+id/linear7"
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				android:layout_marginLeft="10dp"
				android:layout_marginTop="5dp"
				android:layout_marginRight="10dp"
				android:layout_marginBottom="5dp"
				android:padding="8dp"
				android:orientation="horizontal">
				<TextView
					android:id="@+id/code_time"
					android:layout_width="wrap_content"
					android:layout_height="wrap_content"
					android:padding="8dp"
					android:text="Get OTP : "
					android:textSize="12sp"
					android:textColor="#000000"
					android:layout_weight="1" />
				<CheckBox
					android:id="@+id/checkbox1"
					android:layout_width="wrap_content"
					android:layout_height="wrap_content"
					android:padding="8dp"
					android:text="Remember me"
					android:textSize="10sp"
					android:textStyle="bold"
					android:textColor="#000000" />
			</LinearLayout>
			<LinearLayout
				android:id="@+id/v_btn"
				android:layout_width="match_parent"
				android:layout_height="45dp"
				android:layout_marginLeft="13dp"
				android:layout_marginTop="15dp"
				android:layout_marginRight="13dp"
				android:layout_marginBottom="15dp"
				android:paddingLeft="8dp"
				android:paddingRight="8dp"
				android:background="#FFD600"
				android:gravity="center_horizontal|center_vertical"
				android:orientation="horizontal">
				<ProgressBar
					android:id="@+id/progressbar1"
					android:layout_width="wrap_content"
					android:layout_height="30dp"
					android:indeterminate="true"
					style="?android:progressBarStyle"
					android:visibility="gone"
					android:indeterminateTintMode="src_atop"
					android:indeterminateTint="#ffffff" />
				<TextView
					android:id="@+id/verify_txt"
					android:layout_width="wrap_content"
					android:layout_height="wrap_content"
					android:paddingLeft="8dp"
					android:paddingTop="10dp"
					android:paddingRight="8dp"
					android:paddingBottom="10dp"
					android:gravity="center_horizontal|center_vertical"
					android:text="Continue"
					android:textSize="16sp"
					android:textStyle="bold"
					android:textColor="#000000"
					android:layout_weight="1" />
			</LinearLayout>
		</LinearLayout>
	</ScrollView>
</LinearLayout>

**Comment by AndroXStudiO** [comment] 2022-09-02 07:00
<LinearLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	xmlns:tools="http://schemas.android.com/tools"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:orientation="vertical">
	<ScrollView
		android:id="@+id/vscroll1"
		android:layout_width="match_parent"
		android:layout_height="match_parent">
		<LinearLayout
			android:id="@+id/linear1"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:paddingLeft="15dp"
			android:paddingTop="8dp"
			android:paddingRight="15dp"
			android:paddingBottom="25dp"
			android:background="#FFFFFF"
			android:gravity="center_horizontal|center_vertical"
			android:orientation="vertical">
			<com.google.android.material.textfield.TextInputLayout
				android:id="@+id/textinputlayout1"
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				android:layout_marginLeft="10dp"
				android:layout_marginTop="18dp"
				android:layout_marginRight="10dp"
				android:padding="2dp"
				style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
				app:startIconDrawable="@drawable/ic_call_black"
				app:boxCornerRadiusBottomEnd="8dp"
				app:boxCornerRadiusTopEnd="8dp"
				app:boxCornerRadiusBottomStart="8dp"
				app:boxCornerRadiusTopStart="8dp"
				app:boxStrokeColor="#ffb300"
				app:hintTextColor="#ffb300">
				<EditText
					android:id="@+id/edittext3"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:padding="15dp"
					android:gravity="center_vertical"
					android:text="+880"
					android:textSize="16sp"
					android:textColor="#1F1F1F"
					android:hint="Phone Number"
					android:textColorHint="#454746"
					android:singleLine="true"
					android:inputType="phone"
					android:maxLength="18"
					android:maxLines="1"
					android:digits="+0123456789" />
			</com.google.android.material.textfield.TextInputLayout>
			<LinearLayout
				android:id="@+id/linear8"
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				android:layout_marginLeft="10dp"
				android:layout_marginTop="5dp"
				android:layout_marginRight="10dp"
				android:layout_marginBottom="5dp"
				android:paddingLeft="2dp"
				android:paddingRight="2dp"
				android:gravity="center_vertical"
				android:orientation="horizontal">
				<com.google.android.material.textfield.TextInputLayout
					android:id="@+id/textinputlayout2"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:padding="2dp"
					android:gravity="center_horizontal|center_vertical"
					android:layout_weight="1"
					style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
					app:startIconDrawable="@drawable/ic_password"
					app:boxCornerRadiusBottomEnd="8dp"
					app:boxCornerRadiusTopEnd="8dp"
					app:boxCornerRadiusBottomStart="8dp"
					app:boxCornerRadiusTopStart="8dp"
					app:boxStrokeColor="#ffb300"
					app:hintTextColor="#ffb300">
					<EditText
						android:id="@+id/edittext4"
						android:layout_width="match_parent"
						android:layout_height="wrap_content"
						android:padding="15dp"
						android:gravity="center_vertical"
						android:textSize="16sp"
						android:textColor="#1F1F1F"
						android:hint="Verification Code"
						android:textColorHint="#454746"
						android:singleLine="true"
						android:inputType="phone"
						android:enabled="false"
						android:layout_weight="1"
						android:maxLength="11"
						android:maxLines="1"
						android:digits="+0123456789" />
				</com.google.android.material.textfield.TextInputLayout>
			</LinearLayout>
			<LinearLayout
				android:id="@+id/linear7"
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				android:layout_marginLeft="10dp"
				android:layout_marginTop="5dp"
				android:layout_marginRight="10dp"
				android:layout_marginBottom="5dp"
				android:padding="8dp"
				android:orientation="horizontal">
				<TextView
					android:id="@+id/code_time"
					android:layout_width="wrap_content"
					android:layout_height="wrap_content"
					android:padding="8dp"
					android:text="Get OTP : "
					android:textSize="12sp"
					android:textColor="#000000"
					android:layout_weight="1" />
				<CheckBox
					android:id="@+id/checkbox1"
					android:layout_width="wrap_content"
					android:layout_height="wrap_content"
					android:padding="8dp"
					android:text="Remember me"
					android:textSize="10sp"
					android:textStyle="bold"
					android:textColor="#000000" />
			</LinearLayout>
			<LinearLayout
				android:id="@+id/v_btn"
				android:layout_width="match_parent"
				android:layout_height="45dp"
				android:layout_marginLeft="13dp"
				android:layout_marginTop="15dp"
				android:layout_marginRight="13dp"
				android:layout_marginBottom="15dp"
				android:paddingLeft="8dp"
				android:paddingRight="8dp"
				android:background="#FFD600"
				android:gravity="center_horizontal|center_vertical"
				android:orientation="horizontal">
				<ProgressBar
					android:id="@+id/progressbar1"
					android:layout_width="wrap_content"
					android:layout_height="30dp"
					android:indeterminate="true"
					style="?android:progressBarStyle"
					android:visibility="gone"
					android:indeterminateTintMode="src_atop"
					android:indeterminateTint="#ffffff" />
				<TextView
					android:id="@+id/verify_txt"
					android:layout_width="wrap_content"
					android:layout_height="wrap_content"
					android:paddingLeft="8dp"
					android:paddingTop="10dp"
					android:paddingRight="8dp"
					android:paddingBottom="10dp"
					android:gravity="center_horizontal|center_vertical"
					android:text="Continue"
					android:textSize="16sp"
					android:textStyle="bold"
					android:textColor="#000000"
					android:layout_weight="1" />
			</LinearLayout>
		</LinearLayout>
	</ScrollView>
</LinearLayout>

**Comment by AndroXStudiO** [comment] 2022-09-02 07:00
<LinearLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	xmlns:tools="http://schemas.android.com/tools"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:orientation="vertical">
	<ScrollView
		android:id="@+id/vscroll1"
		android:layout_width="match_parent"
		android:layout_height="match_parent">
		<LinearLayout
			android:id="@+id/linear1"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:paddingLeft="15dp"
			android:paddingTop="8dp"
			android:paddingRight="15dp"
			android:paddingBottom="25dp"
			android:background="#FFFFFF"
			android:gravity="center_horizontal|center_vertical"
			android:orientation="vertical">
			<com.google.android.material.textfield.TextInputLayout
				android:id="@+id/textinputlayout1"
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				android:layout_marginLeft="10dp"
				android:layout_marginTop="18dp"
				android:layout_marginRight="10dp"
				android:padding="2dp"
				style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
				app:startIconDrawable="@drawable/ic_call_black"
				app:boxCornerRadiusBottomEnd="8dp"
				app:boxCornerRadiusTopEnd="8dp"
				app:boxCornerRadiusBottomStart="8dp"
				app:boxCornerRadiusTopStart="8dp"
				app:boxStrokeColor="#ffb300"
				app:hintTextColor="#ffb300">
				<EditText
					android:id="@+id/edittext3"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:padding="15dp"
					android:gravity="center_vertical"
					android:text="+880"
					android:textSize="16sp"
					android:textColor="#1F1F1F"
					android:hint="Phone Number"
					android:textColorHint="#454746"
					android:singleLine="true"
					android:inputType="phone"
					android:maxLength="18"
					android:maxLines="1"
					android:digits="+0123456789" />
			</com.google.android.material.textfield.TextInputLayout>
			<LinearLayout
				android:id="@+id/linear8"
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				android:layout_marginLeft="10dp"
				android:layout_marginTop="5dp"
				android:layout_marginRight="10dp"
				android:layout_marginBottom="5dp"
				android:paddingLeft="2dp"
				android:paddingRight="2dp"
				android:gravity="center_vertical"
				android:orientation="horizontal">
				<com.google.android.material.textfield.TextInputLayout
					android:id="@+id/textinputlayout2"
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					android:padding="2dp"
					android:gravity="center_horizontal|center_vertical"
					android:layout_weight="1"
					style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
					app:startIconDrawable="@drawable/ic_password"
					app:boxCornerRadiusBottomEnd="8dp"
					app:boxCornerRadiusTopEnd="8dp"
					app:boxCornerRadiusBottomStart="8dp"
					app:boxCornerRadiusTopStart="8dp"
					app:boxStrokeColor="#ffb300"
					app:hintTextColor="#ffb300">
					<EditText
						android:id="@+id/edittext4"
						android:layout_width="match_parent"
						android:layout_height="wrap_content"
						android:padding="15dp"
						android:gravity="center_vertical"
						android:textSize="16sp"
						android:textColor="#1F1F1F"
						android:hint="Verification Code"
						android:textColorHint="#454746"
						android:singleLine="true"
						android:inputType="phone"
						android:enabled="false"
						android:layout_weight="1"
						android:maxLength="11"
						android:maxLines="1"
						android:digits="+0123456789" />
				</com.google.android.material.textfield.TextInputLayout>
			</LinearLayout>
			<LinearLayout
				android:id="@+id/linear7"
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				android:layout_marginLeft="10dp"
				android:layout_marginTop="5dp"
				android:layout_marginRight="10dp"
				android:layout_marginBottom="5dp"
				android:padding="8dp"
				android:orientation="horizontal">
				<TextView
					android:id="@+id/code_time"
					android:layout_width="wrap_content"
					android:layout_height="wrap_content"
					android:padding="8dp"
					android:text="Get OTP : "
					android:textSize="12sp"
					android:textColor="#000000"
					android:layout_weight="1" />
				<CheckBox
					android:id="@+id/checkbox1"
					android:layout_width="wrap_content"
					android:layout_height="wrap_content"
					android:padding="8dp"
					android:text="Remember me"
					android:textSize="10sp"
					android:textStyle="bold"
					android:textColor="#000000" />
			</LinearLayout>
			<LinearLayout
				android:id="@+id/v_btn"
				android:layout_width="match_parent"
				android:layout_height="45dp"
				android:layout_marginLeft="13dp"
				android:layout_marginTop="15dp"
				android:layout_marginRight="13dp"
				android:layout_marginBottom="15dp"
				android:paddingLeft="8dp"
				android:paddingRight="8dp"
				android:background="#FFD600"
				android:gravity="center_horizontal|center_vertical"
				android:orientation="horizontal">
				<ProgressBar
					android:id="@+id/progressbar1"
					android:layout_width="wrap_content"
					android:layout_height="30dp"
					android:indeterminate="true"
					style="?android:progressBarStyle"
					android:visibility="gone"
					android:indeterminateTintMode="src_atop"
					android:indeterminateTint="#ffffff" />
				<TextView
					android:id="@+id/verify_txt"
					android:layout_width="wrap_content"
					android:layout_height="wrap_content"
					android:paddingLeft="8dp"
					android:paddingTop="10dp"
					android:paddingRight="8dp"
					android:paddingBottom="10dp"
					android:gravity="center_horizontal|center_vertical"
					android:text="Continue"
					android:textSize="16sp"
					android:textStyle="bold"
					android:textColor="#000000"
					android:layout_weight="1" />
			</LinearLayout>
		</LinearLayout>
	</ScrollView>
</LinearLayout>

**Comment by JavkhlanK** [comment] 2022-09-02 09:39
Looks like a duplicate of #540. Since here are more details, let's track that here.  
I couldn't reproduce that on my device/project, could you maybe create an SWB of a project where that's happening and share it here?

**Comment by AndroXStudiO** [comment] 2022-09-02 09:46
i dnt know why...but now its working fine🤔

**Comment by subhash16** [comment] 2022-11-06 17:38
Close this issue he confirmed working above.
And we did not face this kind of issues.

**Comment by JavkhlanK** [comment] 2022-11-06 17:39
I saw multiple reports containing a similar stack trace, so no, I'm not closing this.

**Comment by hasrat-ali** [comment] 2023-07-29 03:08
Keeping this issue open until new version released.

**Closed** 2024-06-25 12:29 UTC
Labels: bug, fixed
