### ISSUE TITLE
hello how do I solve this error when creating the apk

### ISSUE THREAD

**Issue by sammyuk5** [Sketchware-Pro/Sketchware-Pro#916] opened 2023-07-16 21:21 UTC
java.io.IOException: Cannot run program "/data/user/0/com.sketchware.remod/cache/aapt2": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
	at mod.agus.jcoderz.lib.BinaryExecutor.execute(BinaryExecutor.java:19)
	at mod.jbk.build.compiler.resource.ResourceCompiler$Aapt2Compiler.compileImportedResources(ResourceCompiler.java:396)
	at mod.jbk.build.compiler.resource.ResourceCompiler$Aapt2Compiler.compile(ResourceCompiler.java:131)
	at mod.jbk.build.compiler.resource.ResourceCompiler.compile(ResourceCompiler.java:61)
	at a.a.a.Dp.compileResources(Dp.java:157)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1023)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1176)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:928)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 15 more

**Comment by JavkhlanK** [comment] 2023-07-16 21:52
Duplicate of #862.

**Closed** 2023-07-16 21:52 UTC
