### ISSUE TITLE
Firebase SDK update

### ISSUE THREAD

**Issue by PrakharDoneria** [Sketchware-Pro/Sketchware-Pro#724] opened 2023-01-26 06:46 UTC
Please upload Firebase SDK to latest version [https://github.com/firebase/firebase-android-sdk](https://github.com/firebase/firebase-android-sdk) since i was facing issue with FCM while using Sketchware latest version i mailed Firebase and they said to update Firebase SDK version.

**Comment by TechnicalStudioDevelopers** [comment] 2023-01-26 07:02
@JavkhlanK should release Sketchware pro update(Version v6.4.0-rc06-minApi26) because he added feature to exclude in-built library.By using this you can add your custom library version with LibraryManager.

**Comment by PranavPurwar** [comment] 2023-01-26 07:13
@PrakharDoneria @TechnicalStudioDevelopers use snapshot builds

**Comment by PrakharDoneria** [comment] 2023-01-26 07:15
@PranavPurwar how and where to add?

**Comment by TechnicalStudioDevelopers** [comment] 2023-01-26 07:16
> @PrakharDoneria @TechnicalStudioDevelopers use snapshot builds

I don't know github perfectly

**Comment by TechnicalStudioDevelopers** [comment] 2023-01-26 07:22
> @PranavPurwar how and where to add?

I think he is talking about actions in github

**Comment by TechnicalStudioDevelopers** [comment] 2023-01-26 07:28
> @PranavPurwar how and where to add?

Open : https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/3980552762

Scroll down and then download sketchware pre debug apk as your device support then open your project go to library and then below Google Map you will see exclude library option click and remove your FCM library and then go to library manager and download latest version of FCM library and then run project

**Comment by JavkhlanK** [comment] 2023-01-28 22:14
Sort of a duplicate of #469.

**Closed** 2023-01-28 22:15 UTC
Labels: duplicate
