### ISSUE TITLE
New Error after new update

### ISSUE THREAD

**Issue by ZenxDev** [Sketchware-Pro/Sketchware-Pro#289] opened 2021-12-24 02:46 UTC
Error while I want to build my project

**Comment by ZenxDev** [comment] 2021-12-24 02:57
/data/user/0/com.sketchware.remod/files/libs/libs/appcompat-1.0.0/res: error: failed to open directory: No such file or directory.

**Comment by khaled-0** [comment] 2021-12-24 02:59
Try uninstalling then reinstalling the app

**Comment by ZenxDev** [comment] 2021-12-24 03:05
> Try uninstalling then reinstalling the app

Still same error

**Comment by JavkhlanK** [comment] 2021-12-25 07:47
Does Sketchware Pro v6.4.0-rc01 still raise that issue?

**Comment by ZenxDev** [comment] 2021-12-26 10:38
> Does Sketchware Pro v6.4.0-rc01 still raise that issue?

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sketchware.remod/com.besome.sketch.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2517)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
	at android.app.ActivityThread.access$1000(ActivityThread.java:166)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5619)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference
	at mod.hilal.saif.activities.tools.ConfigActivity.isSettingEnabled(ConfigActivity.java:99)
	at com.besome.sketch.MainActivity.onCreate(MainActivity.java:290)
	at android.app.Activity.performCreate(Activity.java:6351)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
	... 9 more

**Comment by PranavPurwar** [comment] 2021-12-26 12:17
it has been fixed in v6.4.0-rc01

**Comment by ZenxDev** [comment] 2021-12-26 12:28
> it will be fixed in v6.4.0 final release

Update apk on release

**Comment by ZenxDev** [comment] 2021-12-26 12:29
> it will be fixed in v6.4.0 final release

Okay, I'll wait..but for now I am using AIDE

**Comment by MikeAndrson** [comment] 2021-12-26 12:47
OK (my name is mike btw)

**Comment by ZenxDev** [comment] 2021-12-26 12:49
Hmm..okay?

**Comment by JavkhlanK** [comment] 2021-12-26 13:07
@ZenxDev, could you check if Sketchware Pro was granted Storage access?

**Comment by ZenxDev** [comment] 2021-12-26 13:47
> @ZenxDev, could you check if Sketchware Pro was granted Storage access?

@JavkhlanK It's working!!...And now I will close this issue

**Closed** 2021-12-26 13:47 UTC
Labels: bug, question, fixed

**Comment by JavkhlanK** [comment] 2021-12-26 13:49
Wait, I've got one last question: Compiling works fine, and you're not getting the original error from this Issue anymore, right?

**Comment by ZenxDev** [comment] 2021-12-26 13:57
> Wait, I've got one last question: Compiling works fine, and you're not getting the original error from this Issue anymore, right?

Yes, I hope so..

**Comment by JavkhlanK** [comment] 2021-12-28 14:29
Good, seems like this Issue's main bug got fixed.

**Comment by JavkhlanK** [comment] 2022-04-06 14:33
@mursalindev, that's an already known issue in v6.4.0-rc01 and v6.4.0-rc01-kt. See in #298 for more details and a workaround.

**Comment by mursalindev** [comment] 2022-04-07 10:19
My Android version is 6 i can't run the latest version for that i want to
use the beta version.

**Comment by ZenxDev** [comment] 2022-04-07 10:45
@mursalindev Can you show picture or error that you facing up

**Comment by mursalindev** [comment] 2022-04-07 10:51
/data/user/0/com.sketchware.remod/files/libs/libs/appcompat-1.0.0/res:
error *:* failed to open directory: No such file or directory.

**Comment by mursalindev** [comment] 2022-04-07 10:51
Sure, here it is.

Text


/data/user/0/com.sketchware.remod/files/libs/libs/appcompat-1.0.0/res:
*error:* failed to open directory: No such file or directory.

**Comment by JavkhlanK** [comment] 2022-04-07 11:22
And what Sketchware Pro version did you use @mursalindev? Make sure it's v6.4.0-rc01 or v6.4.0-rc01-kt.

**Comment by Belu-momhn** [comment] 2023-08-02 20:55
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by Belu-momhn** [comment] 2023-08-02 20:55
<details><summary>sketchware</summary>
<p>

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sketchware.remod/com.besome.sketch.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2517)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
at android.app.ActivityThread.access$1000(ActivityThread.java:166)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5619)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference
at mod.hilal.saif.activities.tools.ConfigActivity.isSettingEnabled(ConfigActivity.java:99)
at com.besome.sketch.MainActivity.onCreate(MainActivity.java:290)
at android.app.Activity.performCreate(Activity.java:6351)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
... 9 more

</p>
</details>

**Comment by Belu-momhn** [comment] 2023-08-08 16:30
- [ ] fix open error 
- [ ] max open
- [ ] None
Settings Error sketchware

**Comment by Belu-momhn** [comment] 2023-08-08 16:33
Can't sketchware uninstall info
- [ ] Open list apps
- [ ] try again
- [ ] what new..
- [ ] Exit <

**Comment by JavkhlanK** [comment] 2023-08-08 17:02
@Belu-momhn please stop spamming nonesense, thanks

**Comment by Belu-momhn** [comment] 2023-08-16 17:20
```
Closed
[New Error after new update](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/289#top)
#289
[ZenxDev](https://github.com/ZenxDev) opened this issue on Dec 24, 2021 · 24 comments
Labels
[bug](https://github.com/Sketchware-Pro/Sketchware-Pro/labels/bug)
[fixed](https://github.com/Sketchware-Pro/Sketchware-Pro/labels/fixed)
Comments
[ZenxDev](https://github.com/ZenxDev) commented [on Dec 24, 2021](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/289#issue-1088107196)
Error while I want to build my project

[ZenxDev](https://github.com/ZenxDev) commented [on Dec 24, 2021](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/289#issuecomment-1000622684)
/data/user/0/com.sketchware.remod/files/libs/libs/appcompat-1.0.0/res: error: failed to open directory: No such file or directory.

[khaled-0](https://github.com/khaled-0) commented [on Dec 24, 2021](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/289#issuecomment-1000623191)
Try uninstalling then reinstalling the app

[ZenxDev](https://github.com/ZenxDev) commented [on Dec 24, 2021](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/289#issuecomment-1000625111)
Try uninstalling then reinstalling the app

Still same error

[JavkhlanK](https://github.com/JavkhlanK) commented [on Dec 25, 2021](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/289#issuecomment-1000986719)
Does Sketchware Pro v6.4.0-rc01 still raise that issue?

@[JavkhlanK](https://github.com/JavkhlanK) JavkhlanK added [bug](https://github.com/Sketchware-Pro/Sketchware-Pro/labels/bug) [pending question(s)](https://github.com/Sketchware-Pro/Sketchware-Pro/labels/pending%20question%28s%29) [fixed](https://github.com/Sketchware-Pro/Sketchware-Pro/labels/fixed) labels [on Dec 25, 2021](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/289#event-5814638919)
[ZenxDev](https://github.com/ZenxDev) commented [on Dec 26, 2021](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/289#issuecomment-1001151414) • 
Does Sketchware Pro v6.4.0-rc01 still raise that issue?

Nice Christmas icon but error when open
@JavkhlanK

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sketchware.remod/com.besome.sketch.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2517)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
at android.app.ActivityThread.access$1000(ActivityThread.java:166)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5619)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference
at mod.hilal.saif.activities.tools.ConfigActivity.isSettingEnabled(ConfigActivity.java:99)
at com.besome.sketch.MainActivity.onCreate(MainActivity.java:290)
at android.app.Activity.performCreate(Activity.java:6351)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
... 9 more
```

**Comment by Belu-momhn** [comment] 2023-08-16 17:27
### Download v6.4.0-rc05


is sketchware error fix version (**Error_Run_stop**)

**Permission here image error**

![200087307-1b9554ec-9f4a-4663-9f9c-259c23609592](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/133125035/d36da38b-55d7-4459-a80c-462457e18ec3)



[Download](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc05)

**Comment by Belu-momhn** [comment] 2023-08-16 17:33
# Download for android

<details><summary>Download</summary>
<p>

# Download for android
Has Free download sketchware
[Download](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc05) 

</p>
</details>
