### ISSUE TITLE
Layouts Menu

### ISSUE THREAD

**Issue by JewelBP** [Sketchware-Pro/Sketchware-Pro#889] opened 2023-06-14 01:01 UTC
YouTube player layout problem in this version. Apk Building success but  After install app not open.

**Comment by TechnicalStudioDeveloper** [comment] 2023-06-14 01:19
You can use [this](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/5261962265) build all to fix your problem I think this might work.

**Comment by JavkhlanK** [comment] 2023-06-14 04:25
Duplicate of #401.

**Closed** 2023-06-14 04:25 UTC
Labels: duplicate
