### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by LincCodes** [Sketchware-Pro/Sketchware-Pro#545] opened 2022-08-20 14:36 UTC
I don't really understand this error coz I DIDN'T even use a Toast (SHOW MESSAGE) in my code, is their a way around this? Please help

**CODE**
java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:157)
	at android.widget.Toast.getLooper(Toast.java:179)
	at android.widget.Toast.<init>(Toast.java:164)
	at android.widget.Toast.makeText(Toast.java:502)
	at android.widget.Toast.makeText(Toast.java:485)
	at tranzit.inter.city.SketchwareUtil.showMessage(SketchwareUtil.java:157)
	at tranzit.inter.city.SketchLogger$1.run(SketchLogger.java:48)

**Comment by JavkhlanK** [comment] 2022-08-20 15:14
Duplicate of #505, and this is a known bug of v6.4.0-rc04. In the meantime, you can turn off debug logs in Build Settings (and then rebuild your project) as a workaround.

**Closed** 2022-08-20 15:14 UTC
Labels: duplicate

**Comment by lahds14** [comment] 2022-08-27 09:22
'Need your help'
