### ISSUE TITLE
Forgot to place the library

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#605] opened 2022-10-08 21:24 UTC
``` java

----------
1. ERROR in /storage/emulated/0/.sketchware/mysc/735/app/src/main/java/com/my/newproject37/MainActivity.java (at line 54)
	private BadgeView badgeview1;
	        ^^^^^^^^^
BadgeView cannot be resolved to a type
----------
2. ERROR in /storage/emulated/0/.sketchware/mysc/735/app/src/main/java/com/my/newproject37/MainActivity.java (at line 96)
	badgeview1 = findViewById(R.id.badgeview1);
	^^^^^^^^^^
BadgeView cannot be resolved to a type
----------
3. ERROR in /storage/emulated/0/.sketchware/mysc/735/app/src/main/java/com/my/newproject37/MainActivity.java (at line 102)
	badgeview1.setVisibility(View.VISIBLE);
	^^^^^^^^^^
BadgeView cannot be resolved to a type
----------
4. ERROR in /storage/emulated/0/.sketchware/mysc/735/app/src/main/java/com/my/newproject37/MainActivity.java (at line 103)
	badgeview1.setBadgeCount(1);
	^^^^^^^^^^
BadgeView cannot be resolved to a type
----------
5. ERROR in /storage/emulated/0/.sketchware/mysc/735/app/src/main/java/com/my/newproject37/MainActivity.java (at line 104)
	badgeview1.setBadgeBackground(0xFFFDA893);
	^^^^^^^^^^
BadgeView cannot be resolved to a type
----------
6. ERROR in /storage/emulated/0/.sketchware/mysc/735/app/src/main/java/com/my/newproject37/MainActivity.java (at line 148)
	badgeview1.setVisibility(View.GONE);
	^^^^^^^^^^
BadgeView cannot be resolved to a type
----------
6 problems (6 errors)

```

You forgot to put this library in your local library. Please do it in the evening. Thanks

**Comment by JavkhlanK** [comment] 2022-10-09 21:32
I just checked in v6.3.0 fix1 and it seems to be expected behavior, though not a really good one in my opinion. Might be good to fix.

**Comment by Arashvscode** [comment] 2022-10-10 10:54
> 

Yes, it is better to make it because it is a beautiful library. I checked the source code and it has only 2 Java files

**Comment by PranavPurwar** [comment] 2022-10-15 14:55
Should remove `expected behaviour` label as it is not relevant to this issue and it's actually a bug.

**Comment by Arashvscode** [comment] 2022-10-16 08:32
Can you delete the Google material and then implement the new version because the Google material of the program is very old. With this and a small code in the styles, you can make major graphic changes in the program.

**Comment by PranavPurwar** [comment] 2022-10-16 09:00
Why don't you just create the pr yourself if you're so desperate about it.

**Comment by Arashvscode** [comment] 2022-10-20 06:27
com.github.bumptech.glide:compiler:4.14.2

 The new version of this library was presented

**Comment by JavkhlanK** [comment] 2022-10-23 09:43
> com.github.bumptech.glide:compiler:4.14.2
> 
> The new version of this library was presented

Glide can't be updated as some classes from Sketchware use `com.bumptech.glide.signature.StringSignature`, which isn't available in any recent Glide version. Using a Gradle dependency of an older Glide version with that class also won't work, as those library versions depend on the support library. Somehow Sketchware got to compile with AndroidX and that old Glide version.

**Comment by PranavPurwar** [comment] 2022-10-23 11:58
> > com.github.bumptech.glide:compiler:4.14.2
> > The new version of this library was presented
> 
> Glide can't be updated as some classes from Sketchware use `com.bumptech.glide.signature.StringSignature`, which isn't available in any recent Glide version. Using a Gradle dependency of an older Glide version with that class also won't work, as those library versions depend on the support library. Somehow Sketchware got to compile with AndroidX and that old Glide version.

jetifier

**Comment by JavkhlanK** [comment] 2022-10-23 19:05
hm wait true

**Comment by Arashvscode** [comment] 2022-10-24 21:58
> > com.github.bumptech.glide:compiler:4.14.2
> > The new version of this library was presented
> 
> Glide can't be updated as some classes from Sketchware use `com.bumptech.glide.signature.StringSignature`, which isn't available in any recent Glide version. Using a Gradle dependency of an older Glide version with that class also won't work, as those library versions depend on the support library. Somehow Sketchware got to compile with AndroidX and that old Glide version.

Disappointed in life

**Comment by JavkhlanK** [comment] 2022-11-19 22:22
Tracks an actual bug, so just ignore the author.

**Closed** 2024-06-30 08:59 UTC
Labels: bug, expected behavior
