### ISSUE TITLE
App doesn't compile if Location Manager Component is used in App.

### ISSUE THREAD

**Issue by InfiSoftApps** [Sketchware-Pro/Sketchware-Pro#592] opened 2022-09-25 11:00 UTC
![Screenshot_2022-09-25-16-17-57-498_com sketchware remod](https://user-images.githubusercontent.com/114339115/192140117-7d280ceb-916a-4f71-969b-d211143aa870.jpg)

Used Location Manager to get the current GPS location. But app doesn't compile at all and shows error as mentioned in screenshot.

**Comment by JavkhlanK** [comment] 2022-09-25 11:51
Which version did you use? If it's a snapshot build, use the latest one, as this bug was fixed already.

**Comment by InfiSoftApps** [comment] 2022-09-25 11:54
![Screenshot_2022-09-25-17-24-46-843_com miui securitycenter](https://user-images.githubusercontent.com/114339115/192142101-4a20f900-7d86-47b3-b068-b9a21a89d833.jpg)

This is the version I'm using. Pleass suggest if any changes required.

**Comment by JavkhlanK** [comment] 2022-09-25 11:57
Wait for v6.4.0-rc05 then. It's a known issue of that version. Duplicate of #582.

**Closed** 2022-09-25 11:57 UTC
Labels: duplicate
