### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by EmStudio22** [Sketchware-Pro/Sketchware-Pro#707] opened 2023-01-14 11:22 UTC
can you fix this

**Comment by EmStudio22** [comment] 2023-01-14 11:22
![Uploading Screenshot_20230114_190017_com.android.chrome.jpg…]()

**Comment by EmStudio22** [comment] 2023-01-14 11:24
![Screenshot_20230114_190017_com android chrome](https://user-images.githubusercontent.com/114802272/212469577-cc554f07-dec1-4bae-a30b-15cee648a114.jpg)

**Comment by JavkhlanK** [comment] 2023-01-14 11:25
Duplicate of #705.

**Closed** 2023-01-14 11:25 UTC
Labels: duplicate
