### ISSUE TITLE
Sounds bugged / get corrupted 

### ISSUE THREAD

**Issue by XenonDry** [Sketchware-Pro/Sketchware-Pro#372] opened 2022-04-26 14:43 UTC
Sounds are bugged. When I add them and leave the sound list the sounds get corrupted and it says 00:00 duration

**Comment by JavkhlanK** [comment] 2022-04-26 17:26
What Android version is your device?

**Comment by JavkhlanK** [comment] 2022-04-26 18:57
Okay, that sounds like a duplicate of #249 then. The reason for Sound Manager and Font Manager not working on newer Android versions is that they use outdated code to get the picked file's path using a workaround (which stopped working, as you can see).

We're aware of that issue, but fixing them isn't very easy. We have to decompile classes, test that code out, and also format it to not look like an abomination.

**Comment by Arashvscode** [comment] 2022-04-27 15:48
> 

Hello to me which works fine without errors and bugs on my mobile
A10s 
Android 11
Ram 2
Rom 32 gb

**Comment by XenonDry** [comment] 2022-04-28 18:20
Android 12
12 GB Ram
Rom 248

Mr ar ***@***.***> schrieb am Mi., 27. Apr. 2022, 17:49:

**Closed** 2022-04-29 09:12 UTC
Labels: bug, duplicate, vanilla SW bug
