### ISSUE TITLE
Lag Issue

### ISSUE THREAD

**Issue by Sadma-Safi** [Sketchware-Pro/Sketchware-Pro#1012] opened 2023-10-13 15:42 UTC
The latest sketchware pro is extremely laggy . Everytime I open projects it goes black for 3 seconds . And whenever I try to edit an event , it goes Black screen for 5 seconds and sometimes it crashes .

Device and Sketchware Pro-related info:
 - Device: [Realme 8]
 - OS: [Android 13]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26] [ The Latest one ]

**Comment by JavkhlanK** [comment] 2023-10-13 15:51
Duplicate of #984. Like I explained on Telegram, add more details or do not create any new Issue or comment since that's not helpful in trying to fix the problem.

**Closed by JavkhlanK** 2023-10-13 15:51 UTC
