### ISSUE TITLE
Error when working with ImageView

### ISSUE THREAD

**Issue by AnBui2004** [Sketchware-Pro/Sketchware-Pro#1230] opened 2024-08-28 19:07 UTC
This error occurs when making any changes to ImageView in virtual phone screen on projects created in older versions of Sketchware.

Sketchware Pro v6.4.0-SNAPSHOT-3b042c0-minApi26 (150)
base.apk size: 135 MB (135328011 B)
Locale: en_US
SDK version: 34
Brand: Redmi
Manufacturer: Xiaomi
Model: 24069RA21C

```
java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:195)
	at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
	at com.google.android.material.card.MaterialCardView.onMeasure(MaterialCardView.java:211)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28078)
	at com.besome.sketch.editor.view.item.ItemVerticalScrollView.measureChildWithMargins(ItemVerticalScrollView.java:172)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.besome.sketch.editor.view.item.ItemVerticalScrollView.onMeasure(ItemVerticalScrollView.java:244)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28078)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28078)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28078)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28078)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28078)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:28078)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:1031)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28078)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28078)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
	at android.view.View.measure(View.java:28078)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:1031)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:837)
	at android.view.View.measure(View.java:28078)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4797)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3306)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3670)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3004)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10326)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1594)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1603)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1125)
	at android.view.Choreographer.doFrame(Choreographer.java:1030)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1567)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8790)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

**Comment by hasrat-ali** [comment] 2024-09-16 19:16
Duplicate of #1059

**Closed by hasrat-ali** 2024-09-16 19:16 UTC
