### ISSUE TITLE
Application fatal error

### ISSUE THREAD

**Issue by Invisible04** [Sketchware-Pro/Sketchware-Pro#356] opened 2022-04-12 09:34 UTC
App crash after open

**Comment by JavkhlanK** [comment] 2022-04-12 09:38
Need more details. Are you talking about Sketchware Pro or your project made with Sketchware Pro? Which Sketchware Pro version did you use, and anything more about your issue are a must before we can help you.

**Comment by Arashvscode** [comment] 2022-04-15 06:51
> App crash after open

First enter the settings and submit the required permissions, then the program will run well lol

**Comment by khaled-0** [comment] 2022-05-15 10:05
Fixed with rc2

**Comment by JavkhlanK** [comment] 2022-05-15 10:06
Since there hasn't been any response I guess it's a duplicate of #298.

**Closed** 2022-05-15 10:06 UTC
Labels: bug, duplicate, fixed
