### ISSUE TITLE
Long press error

### ISSUE THREAD

**Issue by TechnicalStudioDeveloper** [Sketchware-Pro/Sketchware-Pro#746] opened 2023-02-06 03:26 UTC
Version - Version v6.4.0-SNAPSHOT-7e7f14c-minApi26

In many parts of Sketchware pro it is crashing while long press.

[Video](https://www.dropbox.com/s/oo186qfzu0cs1qa/Screenrecorder-2023-02-06-08-50-51-65%280%29.mp4?dl=0)

**Comment by subhash16** [comment] 2023-02-06 06:28
True

**Comment by JavkhlanK** [comment] 2023-02-07 07:20
Seems to have been caused by the recent wip-deobfuscation merge.

**Comment by JavkhlanK** [comment] 2023-02-12 17:40
Should have been fixed with commit 5a126a2d7176af7ebffdfa1e40574903ebacb0d1.

**Closed** 2023-02-12 17:41 UTC
Labels: bug, fixed
