### ISSUE TITLE
CustomView dialog is crashing

### ISSUE THREAD

**Issue by armanicdev** [Sketchware-Pro/Sketchware-Pro#1038] opened 2023-11-28 03:32 UTC
**Describe the bug**
Can't attach custom views to recyclerview.

1. Step 1 Add a RecyclerView
2. Step 2 Try to attach to a custom view
3. Step 3 Pray

**Screenshots**
https://github.com/Sketchware-Pro/Sketchware-Pro/assets/96264464/ee03a5b0-42cf-4643-a5d5-c5ccb88fbf39

Device and Sketchware Pro-related info:
 - Device: S23 Ultra
 - OS: Android 14
 - Sketchware Pro version: v6.4.0-SNAPSHOT-2d4ff70-minApi26

**Comment by JavkhlanK** [comment] 2023-11-28 05:32
Duplicate of #1025

**Closed by JavkhlanK** 2023-11-28 05:32 UTC
