### ISSUE TITLE
When I click on "customview" in the viewer, it gives an error. 

### ISSUE THREAD

**Issue by adesonob** [Sketchware-Pro/Sketchware-Pro#1052] opened 2023-12-23 23:36 UTC
When I click on "customview" in the viewer, it gives an error. 
I use recyclerview to view firebase data.
![Screenshot_20231223-203307_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/92691301/b3db6d86-77b4-430a-bba9-238a0195a7eb)
![Screenshot_20231223-202946_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/92691301/86834d0e-db8c-4477-b37f-6a3239fbaad6)

**Comment by JavkhlanK** [comment] 2023-12-24 00:15
Duplicate of #1025.

**Closed by JavkhlanK** 2023-12-24 00:15 UTC
