### ISSUE TITLE
Error With D8 and ProGoard

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#552] opened 2022-08-27 16:28 UTC
com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: Lio/Heart/Live/androx/s;onAnimationUpdate(Landroid/animation/ValueAnimator;)V, origin: /storage/emulated/0/.sketchware/mysc/967/bin/classes/io/Heart/Live/androx/r.class
	at Version.fakeStackEntry(Version_3.3.28.java:0)
	at com.android.tools.r8.internal.Bj$$ExternalSyntheticLambda0.apply(Unknown Source:6)
	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:75)
	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:28)
	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:27)
	at com.android.tools.r8.internal.Bj.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.D8.run(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
	at mod.jbk.build.compiler.dex.DexCompiler.compileDexFiles(DexCompiler.java:49)
	at a.a.a.Dp.c(Dp.java:233)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1032)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1152)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:895)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.android.tools.r8.internal.Hc: Class content provided for type descriptor io.Heart.Live.androx.r actually defines class io.Heart.Live.androx.R
	at com.android.tools.r8.internal.sa.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:638)
	at com.android.tools.r8.internal.sa.$r8$lambda$Vuv5peuCPma56EYgpi0GDTKA7HY(Unknown Source:0)
	at com.android.tools.r8.internal.sa$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at com.android.tools.r8.graph.r2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2294)
	at com.android.tools.r8.internal.Pa.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1014)
	at com.android.tools.r8.graph.u2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:42)
	at com.android.tools.r8.graph.u2.$r8$lambda$Om7pZsDGPvHHjYwz2kC-xGpIA_c(Unknown Source:0)
	at com.android.tools.r8.graph.u2$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:101)
	at com.android.tools.r8.internal.Bj.$r8$lambda$yDZyJNT_Aje6K0I63BDclaCIlH4(Unknown Source:0)
	at com.android.tools.r8.internal.Bj$$ExternalSyntheticLambda7.get(Unknown Source:2)
	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:102)
	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:100)
	at com.android.tools.r8.graph.u2.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.internal.Ka.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
	at com.android.tools.r8.internal.La.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.internal.sa.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:8)
	at com.android.tools.r8.internal.sa.get(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
	at com.android.tools.r8.internal.ta.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:28)
	at com.android.tools.r8.graph.B2.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
	at com.android.tools.r8.graph.D$$ExternalSyntheticLambda0.apply(Unknown Source:4)
	at com.android.tools.r8.synthesis.s.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:284)
	at com.android.tools.r8.graph.d.c(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
	at com.android.tools.r8.graph.d.e(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
	at com.android.tools.r8.graph.g.e(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
	at com.android.tools.r8.internal.g2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:27)
	at com.android.tools.r8.internal.g2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:14)
	at com.android.tools.r8.internal.dI.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:31)
	at com.android.tools.r8.internal.dI.$r8$lambda$ECWA19clj2PIiemzY000m820SAQ(Unknown Source:0)
	at com.android.tools.r8.internal.dI$$ExternalSyntheticLambda0.apply(Unknown Source:6)
	at com.android.tools.r8.internal.Sv.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:19)
	at com.android.tools.r8.internal.dI.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:30)
	at com.android.tools.r8.internal.dI.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:194)
	at com.android.tools.r8.internal.dI.$r8$lambda$f0c9Ei0ufHq_9BUo3LdgJXxtimM(Unknown Source:0)
	at com.android.tools.r8.internal.dI$$ExternalSyntheticLambda4.apply(Unknown Source:6)
	at com.android.tools.r8.internal.Sv.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:19)
	at com.android.tools.r8.internal.dI.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:192)
	at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:529)
	at com.android.tools.r8.internal.Un.$r8$lambda$TaCiI068C9AkEE89ezLVEeDPcfM(Unknown Source:0)
	at com.android.tools.r8.internal.Un$$ExternalSyntheticLambda27.get(Unknown Source:12)
	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:102)
	at com.android.tools.r8.internal.Un.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:235)
	at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:448)
	at com.android.tools.r8.internal.pe.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:18)
	at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:314)
	at com.android.tools.r8.internal.K9.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
	at com.android.tools.r8.internal.I9.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
	at com.android.tools.r8.internal.K9.c(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
	at com.android.tools.r8.internal.K9.$r8$lambda$YlMUHk7vnJpoWEP1aHkeK1re0PY(Unknown Source:0)
	at com.android.tools.r8.internal.K9$$ExternalSyntheticLambda0.accept(Unknown Source:6)
	at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:39)
	at com.android.tools.r8.utils.C.$r8$lambda$UBg1g3UiNaEyDFkrovkGPiF9oQo(Unknown Source:0)
	at com.android.tools.r8.utils.C$$ExternalSyntheticLambda7.accept(Unknown Source:2)
	at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:44)
	at com.android.tools.r8.utils.C.$r8$lambda$X758yd4-wB5iizs77sTzF9Y-yPc(Unknown Source:0)
	at com.android.tools.r8.utils.C$$ExternalSyntheticLambda9.a(Unknown Source:2)
	at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:38)
	at com.android.tools.r8.utils.C.$r8$lambda$9m8jv_zBqhOSW4qXJYSSvKW5IK4(Unknown Source:0)
	at com.android.tools.r8.utils.C$$ExternalSyntheticLambda11.call(Unknown Source:6)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1433)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Hc: Class content provided for type descriptor io.Heart.Live.androx.r actually defines class io.Heart.Live.androx.R
		at com.android.tools.r8.D8.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:766)
		at com.android.tools.r8.D8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
		at com.android.tools.r8.D8.$r8$lambda$aRVyB0kFcdZ16P9QfsGc9mHei1I(Unknown Source:0)
		at com.android.tools.r8.D8$$ExternalSyntheticLambda2.run(Unknown Source:6)
		at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:24)
		at com.android.tools.r8.internal.Bj.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
		at com.android.tools.r8.D8.run(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
		at mod.jbk.build.compiler.dex.DexCompiler.compileDexFiles(DexCompiler.java:49)
		at a.a.a.Dp.c(Dp.java:233)
		at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1032)
		at a.a.a.MA.a(Unknown Source:11)
		at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1152)
		at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:895)
		at android.os.AsyncTask$3.call(AsyncTask.java:394)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
		at java.lang.Thread.run(Thread.java:923)
	Caused by: java.util.concurrent.ExecutionException: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Hc: Class content provided for type descriptor io.Heart.Live.androx.r actually defines class io.Heart.Live.androx.R
		at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:997)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:14)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:43)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:41)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:40)
		at com.android.tools.r8.internal.K9.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:43)
		at com.android.tools.r8.internal.K9.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
		at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:263)
		at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:13)
		at com.android.tools.r8.D8.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:645)
		... 18 more
	Caused by: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Hc: Class content provided for type descriptor io.Heart.Live.androx.r actually defines class io.Heart.Live.androx.R
		at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:104)
		at com.android.tools.r8.internal.Un.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:235)
		at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:448)
		at com.android.tools.r8.internal.pe.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:18)
		at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:314)
		at com.android.tools.r8.internal.K9.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
		at com.android.tools.r8.internal.I9.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
		at com.android.tools.r8.internal.K9.c(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
		at com.android.tools.r8.internal.K9.$r8$lambda$YlMUHk7vnJpoWEP1aHkeK1re0PY(Unknown Source:0)
		at com.android.tools.r8.internal.K9$$ExternalSyntheticLambda0.accept(Unknown Source:6)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:39)
		at com.android.tools.r8.utils.C.$r8$lambda$UBg1g3UiNaEyDFkrovkGPiF9oQo(Unknown Source:0)
		at com.android.tools.r8.utils.C$$ExternalSyntheticLambda7.accept(Unknown Source:2)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:44)
		at com.android.tools.r8.utils.C.$r8$lambda$X758yd4-wB5iizs77sTzF9Y-yPc(Unknown Source:0)
		at com.android.tools.r8.utils.C$$ExternalSyntheticLambda9.a(Unknown Source:2)
		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:38)
		at com.android.tools.r8.utils.C.$r8$lambda$9m8jv_zBqhOSW4qXJYSSvKW5IK4(Unknown Source:0)
		at com.android.tools.r8.utils.C$$ExternalSyntheticLambda11.call(Unknown Source:6)
		at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1433)
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Caused by: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Hc: Class content provided for type descriptor io.Heart.Live.androx.r actually defines class io.Heart.Live.androx.R
		at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:104)
		at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:100)
		at com.android.tools.r8.graph.u2.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
		at com.android.tools.r8.internal.Ka.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
		at com.android.tools.r8.internal.La.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
		at com.android.tools.r8.internal.sa.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:8)
		at com.android.tools.r8.internal.sa.get(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
		at com.android.tools.r8.internal.ta.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:28)
		at com.android.tools.r8.graph.B2.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
		at com.android.tools.r8.graph.D$$ExternalSyntheticLambda0.apply(Unknown Source:4)
		at com.android.tools.r8.synthesis.s.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:284)
		at com.android.tools.r8.graph.d.c(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
		at com.android.tools.r8.graph.d.e(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
		at com.android.tools.r8.graph.g.e(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
		at com.android.tools.r8.internal.g2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:27)
		at com.android.tools.r8.internal.g2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:14)
		at com.android.tools.r8.internal.dI.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:31)
		at com.android.tools.r8.internal.dI.$r8$lambda$ECWA19clj2PIiemzY000m820SAQ(Unknown Source:0)
		at com.android.tools.r8.internal.dI$$ExternalSyntheticLambda0.apply(Unknown Source:6)
		at com.android.tools.r8.internal.Sv.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:19)
		at com.android.tools.r8.internal.dI.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:30)
		at com.android.tools.r8.internal.dI.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:194)
		at com.android.tools.r8.internal.dI.$r8$lambda$f0c9Ei0ufHq_9BUo3LdgJXxtimM(Unknown Source:0)
		at com.android.tools.r8.internal.dI$$ExternalSyntheticLambda4.apply(Unknown Source:6)
		at com.android.tools.r8.internal.Sv.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:19)
		at com.android.tools.r8.internal.dI.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:192)
		at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:529)
		at com.android.tools.r8.internal.Un.$r8$lambda$TaCiI068C9AkEE89ezLVEeDPcfM(Unknown Source:0)
		at com.android.tools.r8.internal.Un$$ExternalSyntheticLambda27.get(Unknown Source:12)
		at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:102)
		... 24 more
	[CIRCULAR REFERENCE:com.android.tools.r8.internal.Hc: Class content provided for type descriptor io.Heart.Live.androx.r actually defines class io.Heart.Live.androx.R]

**Comment by JavkhlanK** [comment] 2022-08-27 16:34
Duplicate of #493. This bug was also mentioned in the known bugs of v6.4.0-rc04, by the way.

**Closed** 2022-08-27 16:34 UTC
Labels: duplicate

**Comment by AndroXStudiO** [comment] 2022-08-27 16:36
This is already fixed?

**Comment by JavkhlanK** [comment] 2022-08-27 16:37
Yes, but only in snapshot builds so far. [This comment has more info on that.](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/493#issuecomment-1185804462)
