### ISSUE TITLE
Property not changing orientation of Radiogroup

### ISSUE THREAD

**Issue by lildinti** [Sketchware-Pro/Sketchware-Pro#614] opened 2022-10-17 09:25 UTC
Using version 6.4.0 beta 6
Change orientation property for radiogroup doesn't work. Only displays group in vertical orientation. Only way. to make it work is modifying xml file.  This is the xml fragment for radiogroup using vertical orientation.
`<RadioGroup
       android:id="@+id/radiogroup1"
       android:layout_width="wrap_content"
       android:layout_height="wrap_content"
       android:padding="8dp>`

Notice that there's not orientation attribute although not sure maybe default setting!

XML fragment after changing property value using property palette and rebuilding the app. 

`<RadioGroup
       android:id="@+id/radiogroup1"
       android:layout_width="wrap_content"
       android:layout_height="wrap_content"
       android:padding="8dp>`

More info: the xml fragment is from viewing the xml code using the show source code. 
Now, modify xml using the direct code  editor, add orientation attribute, save, apply and compile and orientation works.
Recompile, check xml and attribute  is gone! even checking Xml using direct code editor.

Bug?
Cheers, 
Lildinti

**Comment by JavkhlanK** [comment] 2022-10-18 07:09
That bug was already fixed with commit 299d341b1948866f15921fdcf5bc41b29c7a0be2, which is in Sketchware Pro v6.4.0-rc04. Please upgrade from v6.4.0 Beta 6 to v6.4.0-rc04.

Duplicate of #446.

**Comment by JavkhlanK** [comment] 2022-10-18 07:13
Confirmed this. Thanks for reporting! Next time, please use a more up-to-date version of Sketchware Pro though, for example v6.4.0-rc04.

**Comment by lildinti** [comment] 2022-10-18 16:23
Thanks for that. However still getting vertical radios with horizontal orientation! Usin 6.4.0-rc04 min api21. Also where the source code editor? Not showing up anymore!
XML fragment still the same. 

Cheers
Lildinti

**Comment by JavkhlanK** [comment] 2022-10-18 17:59
Please see this message on why the Direct Source Code Editor was removed:  
![Screenshot_20221002_195425.png](https://user-images.githubusercontent.com/40118124/196508269-29d4f5e4-512d-445f-80ce-ad394fdc80a3.png)

Message in the Discord server: https://discord.com/channels/790686719753846785/790749749522464779/908817727878201424

**Comment by lildinti** [comment] 2022-10-19 04:05
Thanks for that! any thougghts about the orientation bug? still on in 6.4.0 RC 04...tried phone and 2 different emulators(MEmu and Genymotion) in two different OS (windows 11 and MacOS high sierra).
Cheers,
Lildinti

**Comment by JavkhlanK** [comment] 2022-10-23 09:44
The orientation bug exists and hasn't been fixed yet. I'll try to work on it.

The Java/Kotlin Manager exist in the right drawer when having a project opened, right next to the View Manager or Resource Manager.

**Comment by lildinti** [comment] 2022-10-23 11:41
Thanks heaps, JavkhlanK.

**Comment by JavkhlanK** [comment] 2022-10-26 23:07
I think I've fixed this bug, can you try using the latest snapshot build from [this page](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/3333195921) and tell me if it really was?

**Comment by lildinti** [comment] 2022-10-27 09:18
Hi mate, yes is fixed! Awesome work mate. Thanks heaps. Please close issue. Cheers
Lildinti

**Comment by JavkhlanK** [comment] 2022-10-27 09:20
Thanks for testing. I'll keep this Issue opened until v6.4.0-rc05 which should contain this fix gets released.

**Closed** 2022-11-05 09:21 UTC
Labels: bug, fixed
