### ISSUE TITLE
[feature request] Material Design 3

### ISSUE THREAD

**Issue by K-plus69** [Sketchware-Pro/Sketchware-Pro#814] opened 2023-03-18 23:24 UTC
Hello,
Would it me possible to implement Material you? Like In the background color switcher, there should be a "system color" option.
Would be nice! The apps looks old and need the modern design of android 12/12.1/13/14

**Comment by K-plus69** [comment] 2023-03-18 23:28
`/storage/emulated/0/.sketchware/mysc/601/app/src/main/res/layout/main.xml:16: error: resource style/Widget.MaterialComponents.Button (aka com.my.newproject:style/Widget.MaterialComponents.Button) not found.
/storage/emulated/0/.sketchware/mysc/601/app/src/main/res/layout/main.xml:16: error: attribute backgroundTint (aka com.my.newproject:backgroundTint) not found.
/storage/emulated/0/.sketchware/mysc/601/app/src/main/res/layout/main.xml:16: error: attribute cornerRadius (aka com.my.newproject:cornerRadius) not found.
/storage/emulated/0/.sketchware/mysc/601/app/src/main/res/layout/main.xml:16: error: resource style/TextAppearance.MaterialComponents.Button (aka com.my.newproject:style/TextAppearance.MaterialComponents.Button) not found.
error: failed linking file resources.
`

This happens when the material button is put in the app. I have android 13 AOSP

**Comment by PranavPurwar** [comment] 2023-03-19 05:52
You haven't enabled appcompat and/or have skipped material library in Library excluder

**Comment by PranavPurwar** [comment] 2023-03-19 05:54
@K-plus69 you need to modify styles.xml file using command blocks and set the theme to use MaterialYou

**Comment by K-plus69** [comment] 2023-03-19 10:27
Hi, thanks! I accidentally didn't enabled appCompat

But how do I enable material you?

**Comment by JavkhlanK** [comment] 2023-04-06 08:51
Duplicate of #460.

**Closed** 2023-04-06 08:51 UTC
Labels: duplicate

**Comment by JavkhlanK** [comment] 2023-04-06 09:05
@K-plus69 I just explained how to enable it in #460, check it out.
