### ISSUE TITLE
Compiler doesn't work on S24 Ultra

### ISSUE THREAD

**Issue by D4Co137** [Sketchware-Pro/Sketchware-Pro#1096] opened 2024-02-24 18:36 UTC
Compiler outputs random gibberish. It works perfectly on my Xiaomi Note 9 Pro, but not on this phone. 

I know this same problem was already solved here for another phone, but the link for the solution doesn't work anymore...

Device and Sketchware Pro-related info:
 - Device: Samsung Galaxy S24 Ultra
 - OS: Android 14
 - Sketchware Pro Version: both latest releases

![Screenshot_20240224_193000_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/149958871/ae554858-1f6c-4cd7-8d7a-cdf3688d6266)

**Comment by JavkhlanK** [comment] 2024-02-24 18:49
> both latest releases

Specify the **exact** used version names. Possibly a duplicate of #1024.

**Comment by D4Co137** [comment] 2024-02-24 18:52
Versions:
Sketchware.Pro.v6.4.0-rc05-minApi21.apk
Sketchware.Pro.v6.4.0-rc05-minApi26.apk

It is a duplicate of #1024, but link for the solution provided there doesn't work anymore

**Closed** 2024-02-24 18:53 UTC
Labels: duplicate

**Comment by JavkhlanK** [comment] 2024-02-24 18:54
[This describes how to get nightly builds, hopefully it'll help](https://github.com/Sketchware-Pro/Sketchware-Pro/discussions/931#discussioncomment-6574106).

**Comment by D4Co137** [comment] 2024-02-24 19:07
Ok, tell me if I'm being dumb, but the link in the #1024 doesn't lead to any nightly build... It gives error 404 page not found

**Comment by JavkhlanK** [comment] 2024-02-24 19:11
Ignore that link, it's outdated. I linked a specific nightly build there, but those are time-limited due to storage space reasons.

Just use the link I sent here.

**Comment by D4Co137** [comment] 2024-02-24 21:35
Ok, it figured it out. Sorry but Github is a bit confusing for amateurs... Thank you!

**Comment by X-abelX** [comment] 2024-06-08 17:00
Hola buenas me podrian enviar el mismo enlace esque en mi s24 ultra tampoco funciona. @JavkhlanK please

**Comment by JavkhlanK** [comment] 2024-06-08 17:44
@X-abelX use this link: https://nightly.link/Sketchware-Pro/Sketchware-Pro/workflows/android/main?status=completed

**Comment by X-abelX** [comment] 2024-06-08 17:58
@JavkhlanK muchisimas gracias, si me compila, el archivo .json donde lo añado?

**Comment by JavkhlanK** [comment] 2024-06-08 18:12
@X-abelX what json file

**Comment by X-abelX** [comment] 2024-06-08 18:21
![Screenshot_20240608_201838_RS File Manager](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/121341649/4fde5ec5-c5ac-4790-a139-12d33c3cfbf5)

**Comment by X-abelX** [comment] 2024-06-08 18:22
@JavkhlanK Tampoco me deja subir imagenes a sketchware le intento dar a guardar pero no me deja. Tampoco en el explorador de archivos

**Comment by JavkhlanK** [comment] 2024-06-08 18:32
Ignore the .json file.

**Comment by X-abelX** [comment] 2024-06-08 18:57
@JavkhlanK no me deja subir imagenes aqui le doy a guardar y no hace nada
![Uploading Screenshot_20240608_205704_Sketchware Pro.jpg…]()

**Comment by X-abelX** [comment] 2024-06-08 18:59
![Screenshot_20240608_205820_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/121341649/6861f8d2-d031-42c4-bde6-dad49907b7e5)

**Comment by X-abelX** [comment] 2024-06-08 18:59
Me sale eso al instalar por primera vez

**Comment by JavkhlanK** [comment] 2024-06-08 19:23
@X-abelX are you using Sketchware (Pro) for the first time? Just press "OK"
