### ISSUE TITLE
Sketchware; an error occured → End application 

### ISSUE THREAD

**Issue by 1-2-Tree** [Sketchware-Pro/Sketchware-Pro#352] opened 2022-04-07 02:40 UTC
![Screenshot_2022-04-07-10-38-07-72](https://user-images.githubusercontent.com/94172665/162109461-acae9032-e72f-4905-b707-1843f0b696b1.jpg)

**Comment by JavkhlanK** [comment] 2022-04-07 06:48
Duplicate of #298. Also see that issue for a temporary workaround.

**Closed** 2022-04-07 06:49 UTC
Labels: duplicate
