### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by MuhammadKalimullahkhan** [Sketchware-Pro/Sketchware-Pro#566] opened 2022-09-02 19:19 UTC
When ever I try to add an admob banner or interstitial ads ID the app crashes.

**Comment by JavkhlanK** [comment] 2022-09-02 21:50
Duplicate of #490. This is a known issue of v6.4.0-rc04 as mentioned in the release notes, and will be fixed with v6.4.0-rc05.

**Closed** 2022-09-02 21:51 UTC
Labels: duplicate

**Comment by MuhammadKalimullahkhan** [comment] 2022-09-04 03:22
Ok, thank you sir
