### ISSUE TITLE
Me sale este error ,ni siquiera se que es !

### ISSUE THREAD

**Issue by MashLanzer** [Sketchware-Pro/Sketchware-Pro#1130] opened 2024-05-21 05:36 UTC
**Describe the bug**
(444$()8�8�@�@�@�l�l��|�� �� 8�8� 5!5!���|�� ��  R�td�|�� �� 8�@�P�tdp�p�p�||Q�td���88p��� � �AndroidGNU+2o��,�$��Z���t�t������������������P�����T��������
������t����h����T������������������������2�X������������
�������2�<���$�����2�����������L���������n ���� ����� ���� ����!���$���8$���&����'����(���,��
���p�\����������?������������L�L�����l�H�\����������<�H�@�<�D�|����������������6�������h��������
�������������������<�����D���
����������������8����d���������T	�����	�����
�Td����Xe�����e��
���.�����
�������������������������
����������4���������"�����:����'

**To Reproduce**
1. Compile the application 
2. Step 2
3. Step 3
...

**Expected behavior**

**Screenshots**
If
![Screenshot_20240521_013409_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/152557152/a9b941d7-fbc3-46c3-a814-90c9bec18aec)
 applicable, add screenshots to help explain your problem.

Device and Sketchware Pro-related info:
 - Device: [Samsung galaxy s24 Ultra]
 - OS: [Android 14]
 - Sketchware Pro version: [ v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Additional context**

**Comment by JavkhlanK** [comment] 2024-05-21 05:43
Duplicate of #1024.

**Closed by JavkhlanK** 2024-05-21 05:43 UTC
Labels: duplicate
