### ISSUE TITLE
Bug on v6.4.0-SNAPSHOT-70e0a87-minApi21

### ISSUE THREAD

**Issue by Bobur-777** [Sketchware-Pro/Sketchware-Pro#607] opened 2022-10-09 19:08 UTC
Sketchware Pro version v6.4.0-SNAPSHOT-70e0a87-minApi21 is having an error with blocks, can't even see the error.  A white page opens and Sketchware Pro does not work.
#PleaseFix

**Comment by JavkhlanK** [comment] 2022-10-09 21:23
What kind of Blocks? Could you maybe share that project failing to open as SWB?

**Comment by Bobur-777** [comment] 2022-10-09 21:25
Oh no. I can't share project. But bug is on ListView onBindWithCustomView
and OnItemClick listener

Dush, 10-okt, 2022, 02:23 Javkhlan K. ***@***.***>:

**Comment by JavkhlanK** [comment] 2022-10-09 21:30
Alright, no problem. This is probably a duplicate of #583.

**Closed** 2022-10-09 21:30 UTC
Labels: duplicate
