### ISSUE TITLE
When I select a picture, the screen is stuck with an abnormal flash back.

### ISSUE THREAD

**Issue by anthony-china** [Sketchware-Pro/Sketchware-Pro#1075] opened 2024-01-21 16:40 UTC
The version I use is the latest action version.
The error is reported as follow,
java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:195)
	at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
	at com.google.android.material.card.MaterialCardView.onMeasure(MaterialCardView.java:206)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1240)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28128)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28128)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28128)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28128)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28128)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:28128)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:1031)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28128)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:28128)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
	at android.view.View.measure(View.java:28128)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:1031)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7159)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:823)
	at android.view.View.measure(View.java:28128)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4800)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3293)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3654)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2992)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10469)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1671)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1680)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1191)
	at android.view.Choreographer.doFrame(Choreographer.java:1063)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1650)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8670)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
![Screenshot_2024-01-22-00-38-18-659_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/38490701/ec429e15-aef5-427f-931b-f5db35adca9d)

**Comment by ilyassesalama** [comment] 2024-01-21 19:06
You haven't specified anything related to this crash except for the crash log. At least tell us the steps to reproduce this issue.

**Comment by anthony-china** [comment] 2024-01-21 19:41
Change the control ID and change the picture.

> 除了崩溃日志之外，您没有指定与此崩溃相关的任何内容。至少告诉我们重现这个问题的步骤。

**Comment by ilyassesalama** [comment] 2024-01-21 19:43
I think we'll have an issue to understand each other due to the language barrier. It'd be better to send a screen record.

**Comment by hasrat-ali** [comment] 2024-02-15 13:15
Duplicate of #1059

**Closed by hasrat-ali** 2024-02-15 13:15 UTC
Labels: bug, duplicate
