### ISSUE TITLE
Library Import Issue

### ISSUE THREAD

**Issue by Ohyeah66h** [Sketchware-Pro/Sketchware-Pro#1279] opened 2024-10-09 19:42 UTC
I just tried to import the library ``com.google.android.material:material:1.13.0-alpha06`` through the local library dependency thingy in Sketchware Pro. In the middle of it dependencying the library, the entire app crashes.

Sketchware Pro v6.4.0-SNAPSHOT-9ae23e2-minApi26 (150)
base.apk size: 136 MB (135708217 B)
Locale: en_US
SDK version: 34
Brand: samsung
Manufacturer: samsung
Model: SM-S921B

```
java.io.UncheckedIOException: java.io.IOException: close failed: EIO (I/O error)
	at java.util.zip.ZipFile$CleanableResource.run(ZipFile.java:858)
	at jdk.internal.ref.CleanerImpl$PhantomCleanableRef.performCleanup(CleanerImpl.java:212)
	at jdk.internal.ref.PhantomCleanable.clean(PhantomCleanable.java:133)
	at java.lang.Daemons$FinalizerDaemon.doClean(Daemons.java:388)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:358)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:335)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: close failed: EIO (I/O error)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:313)
	at java.io.RandomAccessFile.close(RandomAccessFile.java:726)
	at java.util.zip.ZipFile$Source.close(ZipFile.java:1460)
	at java.util.zip.ZipFile$Source.release(ZipFile.java:1407)
	at java.util.zip.ZipFile$CleanableResource.run(ZipFile.java:849)
	... 7 more
Caused by: android.system.ErrnoException: close failed: EIO (I/O error)
	at libcore.io.Linux.close(Native Method)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.BlockGuardOs.close(BlockGuardOs.java:113)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:311)
	... 11 more

```

**Comment by RoyTheReal** [comment] 2024-10-09 19:45
Yeah I get the same issue trying to resolve com.google.android.material:material:1.13.0-alpha06 in Sketchware Pro:

Sketchware Pro v6.4.0-SNAPSHOT-9ae23e2-minApi26 (150)
base.apk size: 136 MB (135708217 B)
Locale: en_US
SDK version: 34
Brand: samsung
Manufacturer: samsung
Model: SM-X700

```
java.io.UncheckedIOException: java.io.IOException: close failed: EIO (I/O error)
	at java.util.zip.ZipFile$CleanableResource.run(ZipFile.java:858)
	at jdk.internal.ref.CleanerImpl$PhantomCleanableRef.performCleanup(CleanerImpl.java:212)
	at jdk.internal.ref.PhantomCleanable.clean(PhantomCleanable.java:133)
	at java.lang.Daemons$FinalizerDaemon.doClean(Daemons.java:388)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:358)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:335)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: close failed: EIO (I/O error)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:313)
	at java.io.RandomAccessFile.close(RandomAccessFile.java:726)
	at java.util.zip.ZipFile$Source.close(ZipFile.java:1460)
	at java.util.zip.ZipFile$Source.release(ZipFile.java:1407)
	at java.util.zip.ZipFile$CleanableResource.run(ZipFile.java:849)
	... 7 more
Caused by: android.system.ErrnoException: close failed: EIO (I/O error)
	at libcore.io.Linux.close(Native Method)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.BlockGuardOs.close(BlockGuardOs.java:113)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:311)
	... 11 more

```

**Comment by Ohyeah66h** [comment] 2024-10-09 19:49
This sucks. Same issue with trying to import androidx.activity:activity:1.9.2 and other libraries:
Sketchware Pro v6.4.0-SNAPSHOT-9ae23e2-minApi26 (150)
base.apk size: 136 MB (135708217 B)
Locale: en_US
SDK version: 34
Brand: samsung
Manufacturer: samsung
Model: SM-X700

```
java.io.UncheckedIOException: java.io.IOException: close failed: EIO (I/O error)
	at java.util.zip.ZipFile$CleanableResource.run(ZipFile.java:858)
	at jdk.internal.ref.CleanerImpl$PhantomCleanableRef.performCleanup(CleanerImpl.java:212)
	at jdk.internal.ref.PhantomCleanable.clean(PhantomCleanable.java:133)
	at java.lang.Daemons$FinalizerDaemon.doClean(Daemons.java:388)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:358)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:335)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: close failed: EIO (I/O error)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:313)
	at java.io.RandomAccessFile.close(RandomAccessFile.java:726)
	at java.util.zip.ZipFile$Source.close(ZipFile.java:1460)
	at java.util.zip.ZipFile$Source.release(ZipFile.java:1407)
	at java.util.zip.ZipFile$CleanableResource.run(ZipFile.java:849)
	... 7 more
Caused by: android.system.ErrnoException: close failed: EIO (I/O error)
	at libcore.io.Linux.close(Native Method)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.BlockGuardOs.close(BlockGuardOs.java:113)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:311)
	... 11 more

```

**Comment by Ohyeah66h** [comment] 2024-10-09 19:50
@JavkhlanK @hasrat-ali Importing local libraries is broken (dependency thingy is broken)

**Comment by JavkhlanK** [comment] 2024-10-09 20:21
hi can you please stop pinging me for issues you have? i (and neither Hasrat) am not the only maintainer of the app, and in my case, I don't want to deal with issues/support around it too much anymore. just leave normal comments, the right people will get appropriate notifications anyway (because I get an email AND a push notification for pings, which I don't want)

not pinging specific people (unless replying, inactivity, etc.) is part of the general etiquette (on GitHub) anyway afaik

**Comment by hasrat-ali** [comment] 2024-10-11 02:52
duplicate of #1264

**Closed by hasrat-ali** 2024-10-11 02:52 UTC

**Comment by RoyTheReal** [comment] 2024-10-11 12:57
This is still happening in the latest snapshots though
