### ISSUE TITLE
Failed to compile app with App Compat

### ISSUE THREAD

**Issue by syxhri** [Sketchware-Pro/Sketchware-Pro#981] opened 2023-09-17 02:37 UTC
I created a chat application using RecyclerView and App Compat. But when I run it it only gets to Building APK and an error like this appears:

> a.a.a.By: Failed to add /data/user/0/com.sketchware.remod/cache/libs/dexs/appcompat-1.4.0.dex
	at a.a.a.Dp.buildApk(Dp.java:622)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1073)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1176)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:928)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

1. Create an app with UI and logic
2. Enable App Compat
3. Compile the app
...

Expected behavior:
Successfully compiled the application without errors

Device and Sketchware Pro-related info:
 - Device: Xiaomi Redmi 9
 - OS: Android 12
 - Sketchware Pro version: v6.4.0-rc05-minApi26

**Comment by JavkhlanK** [comment] 2023-09-17 06:42
This is a duplicate of #862.

**Closed** 2023-09-17 06:42 UTC
Labels: duplicate
