### ISSUE TITLE
error in Proguard

### ISSUE THREAD

**Issue by AdesonBezerra** [Sketchware-Pro/Sketchware-Pro#493] opened 2022-07-07 16:08 UTC
I was using test build 01, when I updated to test build 04 it gave this error.

Caused by: com.android.tools.r8.internal.Hc: Class content provided for type descriptor com.coclew.r actually defines class com.coclew.R

Suppressed: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Hc: Class content provided for type descriptor com.coclew.r actually defines class com.coclew.R

Caused by: java.util.concurrent.ExecutionException: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Hc: Class content provided for type descriptor com.coclew.r actually defines class com.coclew.R

Caused by: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.Hc: Class content provided for type descriptor com.coclew.r actually defines class com.coclew.R

[CIRCULAR REFERENCE:com.android.tools.r8.internal.Hc: Class content provided for type descriptor com.coclew.r actually defines class com.coclew.R]

![Screenshot_20220707-130152_Sketchware Pro](https://user-images.githubusercontent.com/106257193/177819935-9be1f709-1c93-47b6-bcfc-9822d6fe06bc.png)
![Screenshot_20220707-130143_Sketchware Pro](https://user-images.githubusercontent.com/106257193/177819940-f2d3edc3-2504-43e0-a6ab-2c91755a30bf.png)
![Screenshot_20220707-130131_Sketchware Pro](https://user-images.githubusercontent.com/106257193/177819942-6b693d25-2493-4024-a27d-00e1351726aa.png)
![Screenshot_20220707-130103_Sketchware Pro](https://user-images.githubusercontent.com/106257193/177819947-24dd32de-01df-454c-8d24-dcce7e517f07.png)

**Comment by AdesonBezerra** [comment] 2022-07-12 23:44
> Isso já foi mencionado nas notas da versão v6.4.0-rc04 como bug conhecido, mas agora este problema o acompanhará.



> Isso já foi mencionado nas notas da versão v6.4.0-rc04 como bug conhecido, mas agora este problema o acompanhará.

The cd92a4a fix solved part of the problem, now it only has this error attached.
![Screenshot_20220712-203400_Sketchware Pro](https://user-images.githubusercontent.com/106257193/178616629-81eb705d-577b-4968-a922-789837a7a9ab.png)
![Screenshot_20220712-203400_Sketchware Pro](https://user-images.githubusercontent.com/106257193/178616629-81eb705d-577b-4968-a922-789837a7a9ab.png)

**Comment by JavkhlanK** [comment] 2022-07-13 14:25
Did you use Kotlin code in that project?

**Comment by AdesonBezerra** [comment] 2022-07-13 14:34
> 

No

**Comment by JavkhlanK** [comment] 2022-07-15 14:18
Alright, I finally got to reproduce that bug. Will try to fix now.

**Comment by AdesonBezerra** [comment] 2022-07-15 14:24
Legal, estou ansioso para poder usar o proguard na nova atualização

**Comment by AdesonBezerra** [comment] 2022-07-15 17:58
> Did you use Kotlin code in that project?

Looks like some google classes use kotlin metadata

**Comment by AdesonBezerra** [comment] 2022-07-15 18:45
![Screenshot_20220715-154339_Sketchware Pro](https://user-images.githubusercontent.com/106257193/179290772-bc677355-dd16-42f8-9b6d-bdfec044604f.png)
![Screenshot_20220715-154339_Sketchware Pro](https://user-images.githubusercontent.com/106257193/179290772-bc677355-dd16-42f8-9b6d-bdfec044604f.png)

**Comment by JavkhlanK** [comment] 2022-07-15 18:47
Can you first open up Local library Manager and note down all enabled Local libraries, then delete /Internal storage/.sketchware/data/<project ID>/local_library, then open Local library Manager again, enable all previously noted down libraries, and try building your project again?

All this, because I think that error isn't related to the ProGuard logic.

**Comment by AdesonBezerra** [comment] 2022-07-15 19:09
It worked

**Comment by AdesonBezerra** [comment] 2022-07-15 19:23
![Uploading Screenshot_20220715-162243_Sketchware Pro.png…]()

**Comment by AdesonBezerra** [comment] 2022-07-15 19:25
it only worked after I disabled those options.

![Screenshot_20220715-162243_Sketchware Pro](https://user-images.githubusercontent.com/106257193/179297025-7aee019d-4c43-43e8-a838-615995fa1bad.png)

**Comment by AdesonBezerra** [comment] 2022-08-01 14:47
There is no need to encrypt the libraries, so I believe this issue has been resolved.

**Comment by JavkhlanK** [comment] 2022-08-19 15:01
Okay, got to reproduce that one as well. I'll work on it, and no, it is a bug.

**Comment by AdesonBezerra** [comment] 2022-08-19 15:16
I needed to update firebase to 19.3.0 and proguard doesn't work anymore, as soon as you guys fix this bug, please update firebase too, it has a nice feature to use in sk pro.

**Comment by JavkhlanK** [comment] 2022-08-19 15:22
> I needed to update firebase to 19.3.0 and proguard doesn't work anymore, as soon as you guys fix this bug, please update firebase too, it has a nice feature to use in sk pro.

#469, though I don't want to update the versions built-in into Sketchware Pro. Library version upgrades can break stuff, especially if the major version number gets bumped, and I don't want complaints from inexperienced users about their code not working anymore.  
Rather, I'd like to add a "don't include this built-in library" setting for advanced users, which then can use newer (or even older!) Local libraries as replacements instead.

**Comment by AdesonBezerra** [comment] 2022-08-19 15:30
cool

**Comment by JavkhlanK** [comment] 2022-08-20 20:34
The Local library Full mode bug should have been fixed with 8a37753bead86a7a78d0dd7cd4419581b058e8fb, could you please test this build out: https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/2896019714

**Closed** 2022-09-28 15:10 UTC
Labels: bug, ProGuard

**Comment by JavkhlanK** [comment] 2022-09-28 20:08
Was the bug fixed?

**Comment by AdesonBezerra** [comment] 2022-09-28 20:33
Yes

**Comment by JavkhlanK** [comment] 2022-09-28 20:49
Great!
