### ISSUE TITLE
Old library

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#526] opened 2022-08-02 11:25 UTC
![Screenshot_20220802-155401_Sketchware Pro](https://user-images.githubusercontent.com/101287880/182363477-2a763938-4df5-406a-b5e0-888ef816d8d1.jpg)

Hello, please update the libraries to the latest version, thanks

**Comment by AdesonBezerra** [comment] 2022-08-03 00:03
Also update the FirebaseDatabase

**Comment by JavkhlanK** [comment] 2022-08-13 04:51
Duplicate of #469.

**Closed** 2022-08-13 04:51 UTC
Labels: duplicate
