### ISSUE TITLE
Download Library dialog

### ISSUE THREAD

**Issue by AmirSinaRZ** [Sketchware-Pro/Sketchware-Pro#1174] opened 2024-06-26 14:15 UTC
**Describe the bug**
Dependency downloader dialog is not cancelable
In project manager screen.

**Comment by Ohyeah66h** [comment] 2024-06-28 19:15
Duplicate issue. #1146

**Comment by ilyassesalama** [comment] 2024-06-30 12:18
Duplicate of  ##1146 .

**Closed by ilyassesalama** 2024-06-30 12:18 UTC
Labels: duplicate
