### ISSUE TITLE
Sketchware giving malicious output

### ISSUE THREAD

**Issue by PrakharDoneria** [Sketchware-Pro/Sketchware-Pro#713] opened 2023-01-17 18:02 UTC
As a [Report by Virus Total](https://www.virustotal.com/gui/file/34ca44a8e3fcaf368fa7e6192537763b71f65ebced9bb653e175b929e4650261/detection)  given on a app made using [Sketchware.Pro.v6.4.0-rc05-minApi26](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc05)  the output APK file contains Torzon Horse which flags the file as malicious 
![chrome_screenshot_1673978268213](https://user-images.githubusercontent.com/92568876/212976612-d45785e8-9205-4299-86ae-55eb723e9d48.png)

**Comment by JavkhlanK** [comment] 2023-01-19 11:17
Duplicate of #705.

**Closed** 2023-01-19 11:18 UTC
Labels: duplicate
