### ISSUE TITLE
Bug In Sketchware v6.4.0 test build 5

### ISSUE THREAD

**Issue by HasnatFaiz** [Sketchware-Pro/Sketchware-Pro#780] opened 2023-02-24 15:58 UTC
Youtube Player Widget is not working without signing app.

**Comment by JavkhlanK** [comment] 2023-02-24 15:59
Duplicate of #401.

**Closed by JavkhlanK** 2023-02-24 15:59 UTC

**Comment by TechnicalStudioDeveloper** [comment] 2023-03-16 13:51
Fixed in [pull request](https://github.com/Sketchware-Pro/Sketchware-Pro/pull/810)
