### ISSUE TITLE
YouTube player not work

### ISSUE THREAD

**Issue by LincCodes** [Sketchware-Pro/Sketchware-Pro#737] opened 2023-01-30 10:41 UTC
The YouTube player is not working in the current version of Sketchware.

**Comment by JavkhlanK** [comment] 2023-01-30 18:17
Duplicate of #401. Please also refrain from posting Issues only saying "doesn't work", tell what/why exactly it isn't working, so in this case, that the built app crashes immediately after opening.

**Closed** 2023-01-30 18:17 UTC
Labels: duplicate
