### ISSUE TITLE
Crashing when downloading Glide dependencies

### ISSUE THREAD

**Issue by denzkie2003** [Sketchware-Pro/Sketchware-Pro#1310] opened 2024-10-21 22:15 UTC
- Infinix Hot 40i
- Android 13
- Sketchware Pro v6.4.0-SNAPSHOT-bee414c-miniAPI26

Crashing when trying to download Glide dependencies or Material 1.9.0

** Error for Glide **

Sketchware Pro v6.4.0-SNAPSHOT-bee414c-minApi26 (150)
base.apk size: 136 MB (136131923 B)
Locale: en_US
SDK version: 33
Brand: Infinix
Manufacturer: INFINIX
Model: Infinix X6528

```
java.io.UncheckedIOException: java.io.IOException: close failed: ENOENT (No such file or directory)
	at java.util.zip.ZipFile$CleanableResource.run(ZipFile.java:858)
	at jdk.internal.ref.CleanerImpl$PhantomCleanableRef.performCleanup(CleanerImpl.java:212)
	at jdk.internal.ref.PhantomCleanable.clean(PhantomCleanable.java:133)
	at java.lang.Daemons$FinalizerDaemon.doClean(Daemons.java:388)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:358)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:335)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: close failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:313)
	at java.io.RandomAccessFile.close(RandomAccessFile.java:726)
	at java.util.zip.ZipFile$Source.close(ZipFile.java:1460)
	at java.util.zip.ZipFile$Source.release(ZipFile.java:1407)
	at java.util.zip.ZipFile$CleanableResource.run(ZipFile.java:849)
	... 7 more
Caused by: android.system.ErrnoException: close failed: ENOENT (No such file or directory)
	at libcore.io.Linux.close(Native Method)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.BlockGuardOs.close(BlockGuardOs.java:113)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:311)
	... 11 more

```

**Comment by hasrat-ali** [comment] 2024-11-01 16:13
Duplicate of #1264

**Closed by hasrat-ali** 2024-11-01 16:13 UTC
