### ISSUE TITLE
It's showing new issue

### ISSUE THREAD

**Issue by annikumawat** [Sketchware-Pro/Sketchware-Pro#1031] opened 2023-11-16 01:42 UTC
java.io.IOException: Cannot run program "/data/user/0/com.sketchware.remod/cache/aapt2": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
	at mod.agus.jcoderz.lib.BinaryExecutor.execute(BinaryExecutor.java:19)
	at mod.jbk.build.compiler.resource.ResourceCompiler$Aapt2Compiler.compileBuiltInLibraryResources(ResourceCompiler.java:356)
	at mod.jbk.build.compiler.resource.ResourceCompiler$Aapt2Compiler.compile(ResourceCompiler.java:122)
	at mod.jbk.build.compiler.resource.ResourceCompiler.compile(ResourceCompiler.java:61)
	at a.a.a.Dp.compileResources(Dp.java:157)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1023)
	at a.a.a.MA.a(Unknown Source)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1176)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:928)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
	at java.lang.ProcessImpl.start(ProcessImpl.java:128)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
	... 15 more

**Comment by JavkhlanK** [comment] 2023-11-16 06:00
Duplicate of #862. Also please use the bug report template next time.

**Closed by JavkhlanK** 2023-11-16 06:00 UTC
