### ISSUE TITLE
New version materials redesign is very bad 

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1003] opened 2023-10-09 17:20 UTC
Version v6.4.0-SNAPSHOT-ba123db-minApi26 is very bad, everything is very slow, lots of errors
Sometimes it freezes

**Comment by JavkhlanK** [comment] 2023-10-09 17:27
Create Issues on GitHub only if you can / want to provide more details than what's already available. The same goes for comments. Also, duplicate of #984. Report more details there with comments, and not just "it's laggy for me too"

**Closed by JavkhlanK** 2023-10-09 17:27 UTC
