### ISSUE TITLE
Having some problems in YouTube player😓🥺

### ISSUE THREAD

**Issue by TechnicalStudioDevelopers** [Sketchware-Pro/Sketchware-Pro#421] opened 2022-05-27 05:11 UTC
I am having a problem of YouTube player in sketchware from a long time.When I put the youtube player the complied app get crashed I don't know why This is happening but I if am making mistake then please help me to fix It.

**Comment by m-anshuman2166** [comment] 2022-05-27 09:18
Could you provide a log about same ?

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-27 09:19
> Could you provide a log about same ?

Ok please wait...

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-27 09:26
It's not giving error in Debug log just crashing app when i then app

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-27 09:31
Just try yourself In newer version When you use YouTube player wedget,enabling appCompact then run the compiled app gets crashed after open

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-27 09:40
I have to sign my apk to run it without any error but how can i do it without signing apk file

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-27 09:41
I have to sign my apk to run it without any error but how can i do it without signing apk file

**Comment by JavkhlanK** [comment] 2022-05-27 11:58
Duplicate of #401.

**Closed** 2022-05-27 11:58 UTC
Labels: duplicate

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-27 12:00
I want to add YouTube player without signing 😡😡😡😡😡😡😠😠🤬🤬🤬🤬

**Comment by JavkhlanK** [comment] 2022-05-27 12:04
As far as we know, it's a Sketchware Pro bug not related to signing of the APK.

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-27 12:05
It is related

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-27 12:06
Because Without signing it is YouTube player not working and it is crashing without any debug log

**Comment by JavkhlanK** [comment] 2022-05-27 12:07
Let me check if a release APK doesn't crash when using the YouTube Player View.

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-27 12:09
Check it out please

**Comment by ReduxFlakes** [comment] 2022-05-27 13:47
It's known that it doesn't work.
Use discord to ask those type of questions instead of creating useless GitHub issues that waste the devs time.

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-28 06:05
Have got any solution?

**Comment by TechnicalStudioDevelopers** [comment] 2022-05-28 06:07
What is MT manager?

**Comment by JavkhlanK** [comment] 2022-05-31 12:14
> Let me check if a release APK doesn't crash when using the YouTube Player View.

It really doesn't! Strange. Might try regenerating the library DEX file.
