### ISSUE TITLE
Speech to text not working in android 11,12 and 13

### ISSUE THREAD

**Issue by roopdon49** [Sketchware-Pro/Sketchware-Pro#1072] opened 2024-01-19 11:10 UTC
Speech to text not working in android 11,12 and 13

When increase target SDK 28 to 34. Then, speech to text not working in android 11,12 and 13.
also not come beep sound of start speech recognition.

Device and Sketchware Pro-related info:
 - Device: Xiaomi Note 10
 - OS: Android 13
 - Sketchware Pro version: v6.4.0-rc05-minApi26]

**Comment by hasrat-ali** [comment] 2024-02-15 13:16
Duplicate of #1058

**Closed by hasrat-ali** 2024-02-15 13:16 UTC
