### ISSUE TITLE
Bug In ListView

### ISSUE THREAD

**Issue by Adisdzaky1** [Sketchware-Pro/Sketchware-Pro#1104] opened 2024-03-08 12:25 UTC
![Screenshot_2024-03-08-19-17-10-57](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/128272272/aa312283-8b1b-4991-96c7-b8a34fe0cbfb)

**Describe the bug**
The bug is very annoying when clicking costuView suddenly crashes and exits the application by itself.

**To Reproduce**
1. Step 1 Add ListView
2. Step 2 Then press CustomView 

...

**Expected behavior**
I hope this problem is fixed as soon as possible because it is very annoying for me.

**Screenshots**

Device and Sketchware Pro-related info:
 - Device: Oppo A11K
 - OS: Android 9
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Additional context**

**Comment by hasrat-ali** [comment] 2024-03-09 09:58
Probable duplicate of #1025 .

This is already fixed, try newer build.

**Closed by hasrat-ali** 2024-03-09 09:58 UTC
