### ISSUE TITLE
Admob crash the app when opening

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#971] opened 2023-09-10 14:40 UTC
Latest snapshot
https://github.com/Sketchware-Pro/Sketchware-Pro/commit/4b795fd9d04da46cca283c4268d1c0fd8d339461

java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 

******************************************************************************
* The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
* should follow the instructions here:                                       *
* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
* to add a valid App ID inside the AndroidManifest.                          *
* Google Ad Manager publishers should follow instructions here:              *
* https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
******************************************************************************

	at android.app.ActivityThread.installProvider(ActivityThread.java:7872)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7378)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7111)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.IllegalStateException: 

******************************************************************************
* The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
* should follow the instructions here:                                       *
* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
* to add a valid App ID inside the AndroidManifest.                          *
* Google Ad Manager publishers should follow instructions here:              *
* https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
******************************************************************************

	at com.google.android.gms.ads.internal.client.zzek.attachInfo(com.google.android.gms:play-services-ads-lite@@22.2.0:26)
	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@22.2.0:1)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7867)
	... 11 more

**Comment by subhash16** [comment] 2023-09-10 14:56
Hey I have an idea to fix this and it's working
Open project>
then goto Configuration (three dot)>
AndroidMenifest>
App Components>
Then paste this code

NB:- ca-app-pub-3940256099942544~3347511713
Is your admob app ID

**Comment by JavkhlanK** [comment] 2023-09-10 15:26
Duplicate of #943. Are you OK?

**Closed by JavkhlanK** 2023-09-10 15:26 UTC

**Comment by subhash16** [comment] 2023-09-10 16:00
> Duplicate of #943. Are you OK?

Sorry
