### ISSUE TITLE
APK not building after run

### ISSUE THREAD

**Issue by App-Developer-Ayush** [Sketchware-Pro/Sketchware-Pro#413] opened 2022-05-20 21:10 UTC
Hi GitHub, there is a bug in Sketchware Pro RC03, when I restore a project with path ending .SWB, and when I run it, it doesn't build the apk file and gets crashed.Please fix this bug and update the app.

**Comment by JavkhlanK** [comment] 2022-05-21 06:47
Sounds like a duplicate of #404. Can you try this workaround and tell if that helped: https://github.com/Sketchware-Pro/Sketchware-Pro/issues/404#issuecomment-1128783257

**Comment by 007Shreyas** [comment] 2022-05-21 07:26
Hi @App-Developer-Ayush, same happened to me. And luckily got fixed with help of JavKhlan.
U should uninstall sketchware pro app.. Download the build RC 02 and install.. After that re install the RC 03 build apk directly on the RC 02 (without uninstalling).. This should work perfectly as mine.. No worry as the  Error is already  fixed in the upcoming next update.

**Comment by LincCodes** [comment] 2022-05-21 10:42
> Hi @App-Developer-Ayush, same happened to me. And luckily got fixed with help of JavKhlan.
> U should uninstall sketchware pro app.. Download the build RC 02 and install.. After that re install the RC 03 build apk directly on the RC 02 (without uninstalling).. This should work perfectly as mine.. No worry as the  Error is already  fixed in the upcoming next update. 

Thanks a lot, this actually worked for me too (Using Android v11)

Step 1: Installed RC 02 (with or without AAB, will still work)

Step 2: Opened RC 02 and tried to build and install an app built by Sketchware (You can make a dummy app if you don't have any app)

Step 3: After installing the dummy app using Sketchware, install RC 03 on top of RC 02 (Don't uninstall RC 02, just install RC 03)

Step 4: Congratulations 🎉

**Comment by App-Developer-Ayush** [comment] 2022-05-21 11:54
Thanks man. It worked!

**Comment by Kisunee** [comment] 2022-05-21 15:03
I think it is feature :) not bug..hehe

**Comment by drskin14455** [comment] 2022-05-21 15:28
> same

How to install rc 02?? Sorry I'm a newbie

**Comment by JavkhlanK** [comment] 2022-05-21 22:24
> > same
> 
> How to install rc 02?? Sorry I'm a newbie

You can find the release here: https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc02

**Closed** 2022-05-22 08:41 UTC
Labels: duplicate

**Comment by mkhossainx** [comment] 2022-07-05 06:58
[BUG] Application simply crash when "Aligning APK
