### ISSUE TITLE
App crashes when using ViewPager2 

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1427] opened 2024-11-24 11:40 UTC
**Describe the bug**

In previous versions, I still used ViewPager2 normally, but in recent versions, it has errors.

```
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.view.InflateException: Binary XML file line #70 in com.iMess.in:layout/home: Binary XML file line #70 in com.iMess.in:layout/home: Error inflating class androidx.viewpager2.widget.ViewPager2
Caused by: android.view.InflateException: Binary XML file line #70 in com.iMess.in:layout/home: Error inflating class androidx.viewpager2.widget.ViewPager2
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:876)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1028)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:751)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
	at com.iMess.in.HomeActivity.onCreate(HomeActivity.java:65)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/customview/poolingcontainer/R$id;
	at androidx.customview.poolingcontainer.PoolingContainer.<clinit>(PoolingContainer.kt:121)
	at androidx.customview.poolingcontainer.PoolingContainer.setPoolingContainer(Unknown Source:0)
	at androidx.recyclerview.widget.RecyclerView.<init>(RecyclerView.java:817)
	at androidx.recyclerview.widget.RecyclerView.<init>(RecyclerView.java:739)
	at androidx.recyclerview.widget.RecyclerView.<init>(RecyclerView.java:735)
	at androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl.<init>(ViewPager2.java:973)
	at androidx.viewpager2.widget.ViewPager2.initialize(ViewPager2.java:190)
	at androidx.viewpager2.widget.ViewPager2.<init>(ViewPager2.java:169)
	... 31 more
Caused by: java.lang.ClassNotFoundException: androidx.customview.poolingcontainer.R$id
	... 39 more
```

Device and Sketchware Pro-related info:
 - Device: SamsungA51
 - OS: Android 13
 - Sketchware Pro version: v6.4.0-SNAPSHOT-e907df5-minApi26

**Comment by ilyassesalama** [comment] 2024-11-29 13:26
Duplicated of #1439

**Comment by ilyassesalama** [comment] 2024-11-29 13:26
Duplicate of #1439

**Closed** 2024-11-29 17:05 UTC
Labels: duplicate
