### ISSUE TITLE
Collection Manager Bugs

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1071] opened 2024-01-19 09:27 UTC
**Describe the bug**

https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/22b77e73-cd59-4190-a834-dea35ad8cacc

Entire error message
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sketchware.remod/com.besome.sketch.editor.manage.font.AddFontCollectionActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4166)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4312)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
	at com.besome.sketch.editor.manage.font.AddFontCollectionActivity.onCreate(Unknown Source:122)
	at android.app.Activity.performCreate(Activity.java:8578)
	at android.app.Activity.performCreate(Activity.java:8557)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4147)
	... 12 more

Device and Sketchware Pro-related info:
 - Device: SamSungA51 
 - OS: Android 13
 - Sketchware Pro version: v6.4.0-SNAPSHOT-5460da8-minApi26

**Comment by ilyassesalama** [comment] 2024-01-19 17:51
Should be fixed now. Thanks for the report.

**Closed by ilyassesalama** 2024-01-19 17:51 UTC
Labels: fixed

**Comment by Alotuna** [comment] 2024-01-19 18:19
@ilyassesalama The sound also has the same error

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sketchware.remod/com.besome.sketch.editor.manage.sound.AddSoundCollectionActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setVisibility(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2958)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3093)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6825)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setVisibility(int)' on a null object reference
	at com.besome.sketch.editor.manage.sound.AddSoundCollectionActivity.onCreate(Unknown Source:132)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2938)
	... 11 more
