### ISSUE TITLE
Updating built-in libraries

### ISSUE THREAD

**Issue by PrakharDoneria** [Sketchware-Pro/Sketchware-Pro#994] opened 2023-10-01 13:48 UTC
Sketchware uses too old libraries of Firebase due to which using features like Auth, RTDB, Cloud Storage, FCM doesn't work on high android versions.

Please provide a minor update to Sketchware with new versions of Firebase libs

In addition if possible add some more components and blocks for like in-app messaging and other firebase features.

**Comment by JavkhlanK** [comment] 2023-10-01 19:37
1. Duplicate of #469
2. That exists already. See #993
3. No new built-in Components and/or Blocks will be added (with the exception of e.g. bug fixes), use Custom ones instead.

**Closed by JavkhlanK** 2023-10-01 19:37 UTC
Labels: feature request
