### ISSUE TITLE
Crash during compiling/building apks

### ISSUE THREAD

**Issue by 007Shreyas** [Sketchware-Pro/Sketchware-Pro#404] opened 2022-05-17 08:15 UTC
Dear modders and developers........... 
Issue while compiling and building  any app (apk) on latest version of Sketchware pro v 6.4.0 test build 03.
Detailed report: When 'Run' button is clicked, it apk is successfully compiled(java, dx, aligning already done successfully) but crashes as soon it is signing the apk.. Then Sketchware returns to Home Screen where projects are displayed. NO app is being able to be installed. NO ERROR LOG IS DISPLAYED . Please fix this bug ASAP.

**Comment by khaled-0** [comment] 2022-05-17 08:59
Following
Happened with me once but couldn't replicate or get any logs

**Comment by JavkhlanK** [comment] 2022-05-17 09:10
Please don't mention any maintainers / contributors when opening an Issue. We can see you've opened one already, and mentioning only makes it more intrusive and annoying.

I'm guessing this is due to testkey.zip getting extracted to a new path, but some code still relying on the old path. Will have to investigate further.

**Comment by JavkhlanK** [comment] 2022-05-17 09:11
Could you reproduce the issue and if the app crashes again, upload /Internal storage/.sketchware/debug.txt here?

**Comment by 007Shreyas** [comment] 2022-05-17 09:19
@JavkhlanK sorry to mention you all.. I hust wanted that this issue if fuxed ASAP. And please wait let me try to upload the debug log file

**Comment by JavkhlanK** [comment] 2022-05-17 12:03
Thanks. That confirms my guess, it's trying to use testkey's old file path.

I found out that installing e.g. Sketchware Pro v6.4.0-rc02 directly over v6.4.0-rc03, successfully building a project with it, and then installing v6.4.0-rc03 over it again works.

**Comment by 007Shreyas** [comment] 2022-05-17 13:16
@JavkhlanK is this the only solution. Can't you fix it.

**Comment by JavkhlanK** [comment] 2022-05-17 13:18
Could you please stop mentioning members already?

Anyway, I shared just a workaround for v6.4.0-rc03. The next build, v6.4.0-rc04, will have that bug fixed.

**Comment by 007Shreyas** [comment] 2022-05-17 13:20
I just mentioned you.. I apologize.. Ok thanks... Please release the update soon.(very impatient) and excited for new updates.

**Comment by JavkhlanK** [comment] 2022-05-17 13:26
What I used is a combination of an IDE, some basic knowledge in using search engines, and many hours of reading stuff on e.g. https://developer.android.com or https://stackoverflow.com.

**Comment by 007Shreyas** [comment] 2022-05-17 13:27
And i am not bing able to install over directly.

**Comment by JavkhlanK** [comment] 2022-05-17 20:57
Keeping this open until it's fixed and released.

**Comment by JavkhlanK** [comment] 2022-05-18 08:11
Fixed via 1b44163c9f0e273297ce9603fe5cd6a891da5bb3. Now only awaiting release.

**Closed** 2022-07-05 18:01 UTC
Labels: bug, fixed
