### ISSUE TITLE
All images deleted in data folder

### ISSUE THREAD

**Issue by JamzApps** [Sketchware-Pro/Sketchware-Pro#439] opened 2022-06-05 22:16 UTC
App deleted all my images in xmls so i had to replace them all. It deleted all images in my data folder. This was my biggest app too, so it took all day to add them again.

**Comment by khaled-0** [comment] 2022-07-06 21:19
Also looks more like user fault
Close because not reproducible and dead?

**Comment by JavkhlanK** [comment] 2023-07-23 07:43
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.

**Closed by JavkhlanK** 2023-07-23 07:43 UTC
Labels: help wanted, can't reproduce
