### ISSUE TITLE
Customview error 🤷‍♂️😕

### ISSUE THREAD

**Issue by MdRahulIslam01** [Sketchware-Pro/Sketchware-Pro#1055] opened 2024-01-06 12:18 UTC
Customview error 🤷‍♂️😕

java.lang.NoSuchMethodError: No direct method <init>(Landroid/app/Activity;)V in class La/a/a/aB; or its super classes (declaration of 'a.a.a.aB' appears in /data/app/com.sketchware.remod-qLdhpPm6aToL2UINlmyZdQ==/base.apk!classes5.dex)
	at a.a.a.Pw.a(Unknown Source:8)
	at a.a.a.Pw.onClick(Unknown Source:33)
	at android.view.View.performClick(View.java:7146)
	at android.view.View.performClickInternal(View.java:7119)
	at android.view.View.access$3500(View.java:803)
	at android.view.View$PerformClick.run(View.java:27533)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:232)
	at android.app.ActivityThread.main(ActivityThread.java:7441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by JavkhlanK** [comment] 2024-01-06 13:03
Duplicate of #1025.

**Closed by JavkhlanK** 2024-01-06 13:03 UTC
