### ISSUE TITLE
Duplicate component and slow program speed

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#386] opened 2022-05-10 15:33 UTC
![Screenshot_۲۰۲۲۰۵۱۰-۱۹۵۰۳۳_Sketchware Pro](https://user-images.githubusercontent.com/101287880/167666139-3a66d87d-24ef-4887-b02c-799f514394a4.jpg)
![Screenshot_۲۰۲۲۰۵۱۰-۱۹۳۹۳۸_Sketchware Pro](https://user-images.githubusercontent.com/101287880/167666158-f29c2525-05d4-4fab-8684-fa24b584b5b8.jpg)
![Screenshot_۲۰۲۲۰۵۱۰-۱۹۲۰۳۷_Sketchware Pro](https://user-images.githubusercontent.com/101287880/167666166-3d648f34-6b4d-41a9-b334-1c847d200601.jpg)

As you can see in the photos, the speed of the program is so low that my mobile phone is waiting for an error and this is bad
In the second case, I create a duplicate component program. Most of this happens when the program speed is low
I hope you fix this bug

**Comment by Arashvscode** [comment] 2022-05-10 19:18
@JavkhlanK

**Comment by hasrat-ali** [comment] 2022-05-11 03:01
This is what happens when you click fast. So the solution is don't rush and click comfortably.

**Comment by hasrat-ali** [comment] 2022-05-11 03:04
And this issue must be invalid.

**Comment by Arashvscode** [comment] 2022-05-11 06:02
> 



> This is what happens when you click fast. So the solution is don't rush and click comfortably.

I'm not in a hurry at all and these words are really strange to me. This is a big bug. Check it out.

**Comment by Arashvscode** [comment] 2022-05-11 06:03
> 

Wait for your @JavkhlanK  to check

**Comment by JavkhlanK** [comment] 2022-05-11 17:24
Duplicate of #377.

**Closed** 2022-05-11 17:25 UTC
Labels: duplicate
