### ISSUE TITLE
Sketchware offices updated 

### ISSUE THREAD

**Issue by Abdalelh1** [Sketchware-Pro/Sketchware-Pro#1175] opened 2024-06-27 13:40 UTC
When will the Sketchware offices be updated, because most of the offices have become very old and do not serve the appropriate purpose, so I hope to update the Sketchware offices, such as the Firebase library and others.

**Comment by JavkhlanK** [comment] 2024-06-27 14:40
1. Please use an Issue template the next time.
2. This is a duplicate of #469

**Closed by JavkhlanK** 2024-06-27 14:40 UTC
